#ifndef __IPCMSG_DATA_TYPE_H__
#define __IPCMSG_DATA_TYPE_H__



#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* End of #ifdef __cplusplus */



#include "MiscDataType.h"
//#include "../AlarmAdapter/MeianAlarmHostDataDefine.h"

//#include "auth.h"

typedef struct{
	uint32_t msgId;
	int (*handle)(void * data,uint32_t dataSize,void * private_data);
}__attribute__((packed))MSG_HANDLE;


enum {
	MSG_ID_REGISTER				= 0,			// register msg
	MSG_ID_UNREGISTER,							// unregister msg

	MSG_ID_SEND_MSG_BASE		= 0x100000,		//send msg
	MSG_ID_SEND_TEST1,
	MSG_ID_SEND_TEST2,
	MSG_ID_SEND_TEST3,
	MSG_ID_SEND_TEST4,
	MSG_ID_SEND_GET_DEV_CAP_CMD,
	MSG_ID_SEND_GET_VIDEO_INPUT_PARAM_CMD,
	MSG_ID_SEND_GET_VIDEO_ENC_PARAM_CMD,
	MSG_ID_SEND_SET_VIDEO_INPUT_PARAM_CMD,
	MSG_ID_SEND_SET_VIDEO_ENC_PARAM_CMD,

	MSG_ID_SEND_GET_ETH_PARAM_CMD,
	MSG_ID_SEND_SET_ETH_PARAM_CMD,
	MSG_ID_SEND_GET_WIFI_PARAM_CMD,
	MSG_ID_SEND_SET_WIFI_PARAM_CMD,
	MSG_ID_SEND_GET_NET_STATUS,
	MSG_ID_SEND_SNAPSHOT_CMD,
	MSG_ID_SEND_GET_SNAPSHOT_IMAGE_QUALITY_CMD,
	MSG_ID_SEND_SET_SNAPSHOT_IMAGE_QUALITY_CMD,
	MSG_ID_SEND_SET_MOTION_DETECT_PARAM_CMD,
	MSG_ID_SEND_GET_MOTION_DETECT_PARAM_CMD,
	MSG_ID_SEND_GET_OSD_CONFIG_CMD,						// 20
	MSG_ID_SEND_SET_OSD_CONFIG_CMD,
	MSG_ID_SEND_SET_NET_ATTR_CMD,
	MSG_ID_SEND_GET_CODEC_ENC_INFO_BY_RECORD,
	MSG_ID_SEND_PLAYBACK_QUERY_CMD,
	MSG_ID_SEND_PLAY_START_CMD,
	MSG_ID_SEND_PLAY_STOP_CMD,
	MSG_ID_SEND_GET_STORAGE_CONFIG_CMD,
	MSG_ID_SEND_SET_STORAGE_CONFIG_CMD,
	MSG_ID_SEND_GET_STORAGE_STATUS_CMD,
	MSG_ID_SEND_SET_IRCUT_MODE,
	MSG_ID_SEND_GET_IRCUT_MODE,
	MSG_ID_SEND_TEST_IRCUT_OPEN,
	MSG_ID_SEND_TEST_IRCUT_CLOSE,
	MSG_ID_SEND_GET_AUDIO_MISC_ATTR,
	MSG_ID_SEND_GET_NET_ATTR_CMD,
	MSG_ID_SEND_GET_MEIAN_PLATFORM_SERVER_CONFIG_CMD,
	MSG_ID_SEND_PLAYBACK_QUERY_DAYS_BY_MONTH,
	MSG_ID_SEND_PLAYBACK_QUERY_RECORD_ITEM_IN_ONE_DAY,
	MSG_ID_SEND_GET_FISHEYE_CALIBRATION_PARAM_CMD,
	MSG_ID_SEND_GET_ALARM_HOST_ALL_PARAM_CMD,
	MSG_ID_SEND_SET_ALARM_HOST_ARM_MODE_CMD,
	MSG_ID_SEND_GET_ALARM_HOST_ARM_MODE_CMD,
	MSG_ID_SEND_GET_MCU_VERSION_CMD,
	MSG_ID_SEND_GET_ALARM_HOST_ARM_STATUS_CMD,
	MSG_ID_SEND_ONVIF_GET_OSD_CONFIG_CMD,
	MSG_ID_SEND_ONVIF_SET_OSD_CONFIG_CMD,
	MSG_ID_SEND_GET_ALARM_HOST_ZONE_STATUS_CMD,
	MSG_ID_SEND_SET_LANGUAGE_CMD,
	MSG_ID_SEND_GET_LANGUAGE_CMD,
	MSG_ID_SEND_ONVIF_GET_GMT_DIFF_CMD,
	MSG_ID_SEND_ONVIF_SET_GMT_DIFF_CMD,
	MSG_ID_SEND_GET_ALARM_DEVICES_CMD,
	MSG_ID_SEND_GET_ALARM_ZONES_LINKAGE_CMD,
	MSG_ID_SEND_SET_ALARM_ZONES_LINKAGE_CMD,
	MSG_ID_SEND_ADD_ALARM_DEVICE_CMD,
	MSG_ID_SEND_DEL_ALARM_DEVICE_CMD,
	MSG_ID_SEND_CONTROL_SWITCH_CMD,
	MSG_ID_SEND_QUERY_DOWNLOAD_FAILED_CMD,
	MSG_ID_SEND_SET_ARM_SCHEDULE_CMD,
	MSG_ID_SEND_GET_ARM_SCHEDULE_CMD,
	MSG_ID_SEND_GET_VENC_TYPE_CMD,
	MSG_ID_SEND_SET_VENC_TYPE_CMD,
	MSG_ID_SEND_GET_VOICE_PROMPT_ATTR_CMD,
	MSG_ID_SEND_SET_VOICE_PROMPT_ATTR_CMD,
	MSG_ID_SEND_GET_PIR_ENABLE_CMD,
	MSG_ID_SEND_SET_PIR_ENABLE_CMD,
	MSG_ID_SEND_GET_ALARM_USER_PHONE_CMD,
	MSG_ID_SEND_SET_ALARM_USER_PHONE_CMD,
	MSG_ID_SEND_GET_SENSETIME_SDK_STATUS_CMD,
	MSG_ID_SEND_QUERY_GUI_STATUS_CMD,
	MSG_ID_SEND_QUERY_FB_STATUS_CMD,
	MSG_ID_SEND_GET_MQTT_ADAPTER_PARAM_REQ,
	MSG_ID_SEND_SET_MQTT_ADAPTER_PARAM_REQ,
	MSG_ID_SEND_GET_DOOR_ELECTRIC_RELAY_PARAM_REQ,
	MSG_ID_SEND_SET_DOOR_ELECTRIC_RELAY_PARAM_REQ,
	MSG_ID_SEND_GET_ACCESS_VOICE_PROMPT_PARAM_REQ,
	MSG_ID_SEND_SET_ACCESS_VOICE_PROMPT_PARAM_REQ,
	MSG_ID_SEND_GET_AI_INPUT_IMAGE_SIZE_REQ,
	MSG_ID_SEND_GET_RF_ID_READER_MODE_REQ,
	MSG_ID_SEND_SET_RF_ID_READER_MODE_REQ,
	MSG_ID_SEND_GET_ALL_RELAYS_CONFIG_REQ,
    MSG_ID_SEND_GUI_GET_SYSTEM_LANG_REQ,
    MSG_ID_SEND_GET_SOUND_PLAY_PARAM_REQ,
    MSG_ID_SEND_SET_SOUND_PLAY_PARAM_REQ,
    MSG_ID_SEND_GET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_REQ,
    MSG_ID_SEND_SET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_REQ,
    MSG_ID_SEND_MQTT_ADD_QR_CODE_REQ,
    MSG_ID_SEND_GET_FACE_AREA_RATIO_REQ,
    MSG_ID_SEND_SET_FACE_AREA_RATIO_REQ,
    MSG_ID_SEND_GET_BODY_TEMP_SNS_PARAM_REQ,
    MSG_ID_SEND_SET_BODY_TEMP_SNS_PARAM_REQ,
	MSG_ID_SEND_GET_AI_RULES_PARAM_REQ,
	MSG_ID_SEND_SET_AI_RULES_PARAM_REQ,
	MSG_ID_SEND_GET_AI_AREAS_PARAM_REQ,
	MSG_ID_SEND_SET_AI_AREAS_PARAM_REQ,
	MSG_ID_SEND_GET_AI_ALARM_LINKAGE_PARAM_REQ,
	MSG_ID_SEND_SET_AI_ALARM_LINKAGE_PARAM_REQ,
	MSG_ID_SEND_GET_LINKAGE_SOUND_LIST_REQ,
	MSG_ID_SEND_SET_LINKAGE_SOUND_LIST_REQ,
    MSG_ID_SEND_NVT_SET_INTERFACE_IP_REQ,
    MSG_ID_SEND_NVT_SET_DEFAULT_GW_REQ,
    MSG_ID_SEND_NVT_GET_NETWORK_PARAM_REQ,
	MSG_ID_SEND_GET_IRCUT_PARAM_REQ,
	MSG_ID_SEND_SET_IRCUT_PARAM_REQ,
	MSG_ID_SEND_GET_DAY_NIGHT_STATUS_REQ,
	MSG_ID_SEND_GET_DB_FACE_COUNT_REQ,
	MSG_ID_SEND_GET_FACE_COMPARE_THRESHOLD_REQ,
	MSG_ID_SEND_SET_FACE_COMPARE_THRESHOLD_REQ,
	MSG_ID_SEND_HUIYUN_SNAPSHOT_CMD,
	MSG_ID_SEND_HUIYUN_GET_NET_STATUS,
	MSG_ID_SEND_HUIYUN_GET_NET_ATTR_CMD,
	MSG_ID_SEND_HUIYUN_SET_NET_ATTR_CMD,
	MSG_ID_SEND_HUIYUN_GET_VIDEO_INPUT_PARAM_CMD,
	MSG_ID_SEND_HUIYUN_SET_VIDEO_INPUT_PARAM_CMD,
	MSG_ID_SEND_HUIYUN_GET_VIDEO_ENC_PARAM_CMD,
	MSG_ID_SEND_HUIYUN_SET_VIDEO_ENC_PARAM_CMD,
	MSG_ID_SEND_HUIYUN_GET_IRCUT_MODE,
	MSG_ID_SEND_HUIYUN_SET_IRCUT_MODE,
	MSG_ID_SEND_HUIYUN_GET_AUDIO_MISC_ATTR,
	MSG_ID_SEND_HUIYUN_GET_GMT_DIFF_CMD,
	MSG_ID_SEND_HUIYUN_SET_GMT_DIFF_CMD,
	MSG_ID_SEND_HUIYUN_GET_MOTION_DETECT_PARAM_CMD,
	MSG_ID_SEND_HUIYUN_SET_MOTION_DETECT_PARAM_CMD,
	MSG_ID_SEND_HUIYUN_GET_SIM_ICCID_CMD,
	MSG_ID_SEND_HUIYUN_GET_IMEI_CMD,
	MSG_ID_SEND_HUIYUN_GET_4G_SIGNAL_QUALITY_CMD,
	MSG_ID_SEND_HUIYUN_GET_AI_AREAS_PARAM_REQ,
	MSG_ID_SEND_HUIYUN_SET_AI_AREAS_PARAM_REQ,


	MSG_ID_RESP_MSG_BASE		= 0x200000,		//response msg for send msg
	MSG_ID_RESP_TEST1,
	MSG_ID_RESP_TEST2,
	MSG_ID_RESP_TEST3,
	MSG_ID_RESP_TEST4,
	MSG_ID_RESP_GET_DEV_CAP_CMD,
	MSG_ID_RESP_GET_VIDEO_INPUT_PARAM_CMD,
	MSG_ID_RESP_GET_VIDEO_ENC_PARAM_CMD,
	MSG_ID_RESP_SET_VIDEO_INPUT_PARAM_CMD,
	MSG_ID_RESP_SET_VIDEO_ENC_PARAM_CMD,
	MSG_ID_RESP_GET_ETH_PARAM_CMD,
	MSG_ID_RESP_SET_ETH_PARAM_CMD,
	MSG_ID_RESP_GET_WIFI_PARAM_CMD,
	MSG_ID_RESP_SET_WIFI_PARAM_CMD,	
	MSG_ID_RESP_GET_NET_STATUS,
	MSG_ID_RESP_SNAPSHOT_CMD,
	MSG_ID_RESP_GET_SNAPSHOT_IMAGE_QUALITY_CMD,
	MSG_ID_RESP_SET_SNAPSHOT_IMAGE_QUALITY_CMD,
	MSG_ID_RESP_SET_MOTION_DETECT_PARAM_CMD,
	MSG_ID_RESP_GET_MOTION_DETECT_PARAM_CMD,
	MSG_ID_RESP_GET_OSD_CONFIG_CMD,
	MSG_ID_RESP_SET_OSD_CONFIG_CMD,
	MSG_ID_RESP_SET_NET_ATTR_CMD,
	MSG_ID_RESP_GET_CODEC_ENC_INFO_BY_RECORD,
	MSG_ID_RESP_PLAYBACK_QUERY_CMD,
	MSG_ID_RESP_PLAY_START_CMD,
	MSG_ID_RESP_PLAY_STOP_CMD,
	MSG_ID_RESP_GET_STORAGE_CONFIG_CMD,
	MSG_ID_RESP_SET_STORAGE_CONFIG_CMD,
	MSG_ID_RESP_GET_STORAGE_STATUS_CMD,
	MSG_ID_RESP_SET_IRCUT_MODE,
	MSG_ID_RESP_GET_IRCUT_MODE,
	MSG_ID_RESP_TEST_IRCUT_OPEN,
	MSG_ID_RESP_TEST_IRCUT_CLOSE,
	MSG_ID_RESP_GET_AUDIO_MISC_ATTR,
	MSG_ID_RESP_GET_NET_ATTR_CMD,
	MSG_ID_RESP_GET_MEIAN_PLATFORM_SERVER_CONFIG_CMD,
	MSG_ID_RESP_PLAYBACK_QUERY_DAYS_BY_MONTH,
	MSG_ID_RESP_PLAYBACK_QUERY_RECORD_ITEM_IN_ONE_DAY,
	MSG_ID_RESP_GET_FISHEYE_CALIBRATION_PARAM_CMD,
	MSG_ID_RESP_GET_ALARM_HOST_ALL_PARAM_CMD,
	MSG_ID_RESP_SET_ALARM_HOST_ARM_MODE_CMD,
	MSG_ID_RESP_GET_ALARM_HOST_ARM_MODE_CMD,
	MSG_ID_RESP_GET_MCU_VERSION_CMD,
	MSG_ID_RESP_GET_ALARM_HOST_ARM_STATUS_CMD,
	MSG_ID_RESP_ONVIF_GET_OSD_CONFIG_CMD,
	MSG_ID_RESP_ONVIF_SET_OSD_CONFIG_CMD,
	MSG_ID_RESP_GET_ALARM_HOST_ZONE_STATUS_CMD,
	MSG_ID_RESP_SET_LANGUAGE_CMD,
	MSG_ID_RESP_GET_LANGUAGE_CMD,
	MSG_ID_RESP_ONVIF_GET_GMT_DIFF_CMD,
	MSG_ID_RESP_ONVIF_SET_GMT_DIFF_CMD,
	MSG_ID_RESP_GET_ALARM_DEVICES_CMD,
	MSG_ID_RESP_GET_ALARM_ZONES_LINKAGE_CMD,
	MSG_ID_RESP_SET_ALARM_ZONES_LINKAGE_CMD,
	MSG_ID_RESP_ADD_ALARM_DEVICE_CMD,
	MSG_ID_RESP_DEL_ALARM_DEVICE_CMD,
	MSG_ID_RESP_CONTROL_SWITCH_CMD,
	MSG_ID_RESP_QUERY_DOWNLOAD_FAILED_CMD,
	MSG_ID_RESP_SET_ARM_SCHEDULE_CMD,
	MSG_ID_RESP_GET_ARM_SCHEDULE_CMD,
	MSG_ID_RESP_GET_VENC_TYPE_CMD,
	MSG_ID_RESP_SET_VENC_TYPE_CMD,
	MSG_ID_RESP_GET_VOICE_PROMPT_ATTR_CMD,
	MSG_ID_RESP_SET_VOICE_PROMPT_ATTR_CMD,
	MSG_ID_RESP_GET_PIR_ENABLE_CMD,
	MSG_ID_RESP_SET_PIR_ENABLE_CMD,
	MSG_ID_RESP_GET_ALARM_USER_PHONE_CMD,
	MSG_ID_RESP_SET_ALARM_USER_PHONE_CMD,
	MSG_ID_RESP_GET_SENSETIME_SDK_STATUS_CMD,
	MSG_ID_RESP_QUERY_GUI_STATUS_CMD,
	MSG_ID_RESP_QUERY_FB_STATUS_CMD,
	MSG_ID_RESP_SET_MQTT_ADAPTER_PARAM_RESP,
	MSG_ID_RESP_GET_MQTT_ADAPTER_PARAM_RESP,
	MSG_ID_RESP_GET_DOOR_ELECTRIC_RELAY_PARAM_REQ,
	MSG_ID_RESP_SET_DOOR_ELECTRIC_RELAY_PARAM_REQ,
	MSG_ID_RESP_GET_ACCESS_VOICE_PROMPT_PARAM_REQ,
	MSG_ID_RESP_SET_ACCESS_VOICE_PROMPT_PARAM_REQ,
	MSG_ID_RESP_GET_AI_INPUT_IMAGE_SIZE_RESP,
	MSG_ID_RESP_GET_RF_ID_READER_MODE_REQ,
	MSG_ID_RESP_SET_RF_ID_READER_MODE_REQ,
	MSG_ID_RESP_GET_ALL_RELAYS_CONFIG_REQ,
    MSG_ID_RESP_GUI_GET_SYSTEM_LANG_RESP,
    MSG_ID_RESP_GET_SOUND_PLAY_PARAM_REQ,
    MSG_ID_RESP_SET_SOUND_PLAY_PARAM_REQ,
    MSG_ID_RESP_GET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_REQ,
    MSG_ID_RESP_SET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_REQ,
    MSG_ID_RESP_MQTT_ADD_QR_CODE_REQ,
    MSG_ID_RESP_GET_FACE_AREA_RATIO_REQ,
    MSG_ID_RESP_SET_FACE_AREA_RATIO_REQ,
    MSG_ID_RESP_GET_BODY_TEMP_SNS_PARAM_REQ,
    MSG_ID_RESP_SET_BODY_TEMP_SNS_PARAM_REQ,
	MSG_ID_RESP_GET_AI_RULES_PARAM_REQ,
	MSG_ID_RESP_SET_AI_RULES_PARAM_REQ,
	MSG_ID_RESP_GET_AI_AREAS_PARAM_REQ,
	MSG_ID_RESP_SET_AI_AREAS_PARAM_REQ,
	MSG_ID_RESP_GET_AI_ALARM_LINKAGE_PARAM_REQ,
	MSG_ID_RESP_SET_AI_ALARM_LINKAGE_PARAM_REQ,
	MSG_ID_RESP_GET_LINKAGE_SOUND_LIST_REQ,
	MSG_ID_RESP_SET_LINKAGE_SOUND_LIST_REQ,
    MSG_ID_RESP_NVT_SET_INTERFACE_IP_REQ,
    MSG_ID_RESP_NVT_SET_DEFAULT_GW_REQ,
    MSG_ID_RESP_NVT_GET_NETWORK_PARAM_REQ,
	MSG_ID_RESP_GET_IRCUT_PARAM_REQ,
	MSG_ID_RESP_SET_IRCUT_PARAM_REQ,
	MSG_ID_RESP_GET_DAY_NIGHT_STATUS_REQ,
	MSG_ID_RESP_GET_DB_FACE_COUNT_REQ,
	MSG_ID_RESP_GET_FACE_COMPARE_THRESHOLD_REQ,
	MSG_ID_RESP_SET_FACE_COMPARE_THRESHOLD_REQ,
	MSG_ID_RESP_HUIYUN_SNAPSHOT_CMD,
	MSG_ID_RESP_HUIYUN_GET_NET_STATUS,
	MSG_ID_RESP_HUIYUN_GET_NET_ATTR_CMD,
	MSG_ID_RESP_HUIYUN_SET_NET_ATTR_CMD,
	MSG_ID_RESP_HUIYUN_GET_VIDEO_INPUT_PARAM_CMD,
	MSG_ID_RESP_HUIYUN_SET_VIDEO_INPUT_PARAM_CMD,
	MSG_ID_RESP_HUIYUN_GET_VIDEO_ENC_PARAM_CMD,
	MSG_ID_RESP_HUIYUN_SET_VIDEO_ENC_PARAM_CMD,
	MSG_ID_RESP_HUIYUN_GET_IRCUT_MODE,
	MSG_ID_RESP_HUIYUN_SET_IRCUT_MODE,
	MSG_ID_RESP_HUIYUN_GET_AUDIO_MISC_ATTR,
	MSG_ID_RESP_HUIYUN_GET_GMT_DIFF_CMD,
	MSG_ID_RESP_HUIYUN_SET_GMT_DIFF_CMD,
	MSG_ID_RESP_HUIYUN_GET_MOTION_DETECT_PARAM_CMD,
	MSG_ID_RESP_HUIYUN_SET_MOTION_DETECT_PARAM_CMD,
	MSG_ID_RESP_HUIYUN_GET_SIM_ICCID_CMD,
	MSG_ID_RESP_HUIYUN_GET_IMEI_CMD,
	MSG_ID_RESP_HUIYUN_GET_4G_SIGNAL_QUALITY_CMD,
	MSG_ID_RESP_HUIYUN_GET_AI_AREAS_PARAM_REQ,
	MSG_ID_RESP_HUIYUN_SET_AI_AREAS_PARAM_REQ,

	
	MSG_ID_POST_BASE			= 0x300000,		// post msg ,need not response
	MSG_ID_POST_FORCE_KEY_FRAME,
	MSG_ID_POST_VOICE_PORMPT_CMD,
	MSG_ID_POST_RESET_CMD,
	MSG_ID_POST_RESET_CODEC_MSG,
	MSG_ID_POST_DEVICE_LICENSE_INVALID,
	MSG_ID_POST_DEVICE_LICENSE_VALID,
	MSG_ID_POST_SET_AUDIO_MISC_ATTR,// this command need codec reset..........lifan @2017.08.09
	MSG_ID_POST_SET_SYSTEM_GMT_TIME,
	MSG_ID_POST_SET_FISHEYE_CALIBRATION_PARAM_CMD, // this command need codec reset..........lifan @2018.03.21
	MSG_ID_POST_WIRELESS_DEVICE_MATCH_CODE_STOP_CMD,
	MSG_ID_POST_WIRELESS_DEVICE_MATCH_CODE_START_CMD,
	MSG_ID_POST_SET_ALARM_HOST_ALL_PARAM_CMD,
	MSG_ID_POST_SET_GPRS_STATUS_CMD,
	MSG_ID_POST_EDIT_ALARM_ZONE_PARAM_CMD,
	MSG_ID_POST_NVR_REQ_FRAME_RATE_CMD,
	MSG_ID_POST_SET_ALARM_HOST_SYSTEM_EXT_PARAM_CMD,
	MSG_ID_POST_SET_ALARM_HOST_ALARM_PARAM_CMD,
	MSG_ID_POST_FIRE_SMOKE_BOMB,
	MSG_ID_POST_SET_SOUND_LIGHT_ALARM_CMD,
	MSG_ID_POST_ADD_FACE_CMD,
	MSG_ID_POST_DEL_FACE_CMD,
	MSG_ID_POST_EDIT_FACE_CMD,
	MSG_ID_POST_GET_FACE_LIST_CMD,
	MSG_ID_POST_ADD_FACE_RESULT,
	MSG_ID_POST_DEL_FACE_RESULT,
	MSG_ID_POST_EDIT_FACE_RESULT,
	MSG_ID_POST_CODEC_IMPORT_FACE_DB_FILE_READY,
	MSG_ID_POST_IMPORT_FACE_DB_RESULT,
	MSG_ID_POST_CODEC_NOTIFY_GUI_EXIT_MSG,
	MSG_ID_POST_CODEC_NOTIFY_GUI_FB_WILL_START_MSG,
	MSG_ID_POST_ACCESS_RECORD_PUSH_MSG,
	MSG_ID_POST_ADD_FACE_WITH_JPEG,
	MSG_ID_POST_ADD_FACE_WITH_JPEG_RESULT,
	MSG_ID_POST_SENSETIME_SDK_INIT_STATUS,
	MSG_ID_POST_QUERY_OFFLINE_ACCESS_RECORD_REQ,
	MSG_ID_POST_QUERY_OFFLINE_ACCESS_RECORD_RESP,
	MSG_ID_POST_QUERY_AI_MODULE_READY_REQ,
	MSG_ID_POST_QUERY_AI_MODULE_READY_RESP,
	MSG_ID_POST_QUERY_MQTT_BROKER_STATUS,
	MSG_ID_POST_DELETE_FACE_BY_JINMAO_USER_ID_REQ,
	MSG_ID_POST_DELETE_FACE_BY_JINMAO_USER_ID_RESP,
	MSG_ID_POST_ADD_RF_ID_REQ,
	MSG_ID_POST_ADD_RF_ID_RESP,
	MSG_ID_POST_DEL_RF_ID_REQ,
	MSG_ID_POST_DEL_RF_ID_RESP,
	MSG_ID_POST_REPORT_RF_ID_REQ,
	MSG_ID_POST_CLEAR_FACE_REQ,
	MSG_ID_POST_CLEAR_FACE_RESP,
    MSG_ID_POST_WIFI_POWER_CTRL_REQ,
    MSG_ID_POST_QUERY_BODY_TEMPERATURE_REQ,
    MSG_ID_POST_QUERY_BODY_TEMPERATURE_RESP,
    MSG_ID_POST_MIC_SPEAKER_CTRL_REQ,
	MSG_ID_POST_PTZ_CONTROL_REQ, 
	MSG_ID_POST_QR_CODE_SCANNING_RESULT, 
	MSG_ID_POST_QR_CODE_SCANNING_CTRL_CMD, 
	// post msg get/set eth param , lifan@2021.03.11
	MSG_ID_POST_GET_ETH_PARAM_REQ,
	MSG_ID_POST_GET_ETH_PARAM_RES,
	MSG_ID_POST_SET_ETH_PARAM_REQ,
	MSG_ID_POST_SET_ETH_PARAM_RES,
	// post msg get/set platform param , lifan@2021.03.12
	MSG_ID_POST_GET_PLAT_PARAM_REQ,
	MSG_ID_POST_GET_PLAT_PARAM_RES,
	MSG_ID_POST_SET_PLAT_PARAM_REQ,
	MSG_ID_POST_SET_PLAT_PARAM_RES,

	// post msg get/set mqtt param , lifan@2021.03.12
	MSG_ID_POST_GET_MQTT_PARAM_REQ,
	MSG_ID_POST_GET_MQTT_PARAM_RES,
	MSG_ID_POST_SET_MQTT_PARAM_REQ,
	MSG_ID_POST_SET_MQTT_PARAM_RES,
	//////////////////////////////////////////
	// lifan @2021.03.26
	// just for local gui set/get light ctrl param,gui need post/aysnc msg
	// BAD CODE!!!! (Implementation of these functions does not allow for asynchronous communication for local GUI)
	// BAD CODE!!!! (Implementation of these functions does not allow for asynchronous communication for local GUI)
	// BAD CODE!!!! (Implementation of these functions does not allow for asynchronous communication for local GUI)
	// BAD CODE!!!! (Implementation of these functions does not allow for asynchronous communication for local GUI)
	// BAD CODE!!!! (Implementation of these functions does not allow for asynchronous communication for local GUI)
	// get light param
    MSG_ID_POST_GET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_REQ,
    MSG_ID_POST_GET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_RESULT,
    // set light param
    MSG_ID_POST_SET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_REQ,
    MSG_ID_POST_SET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_RESULT,
    // get face area ratio
    MSG_ID_POST_GET_FACE_AREA_RATIO_REQ,
    MSG_ID_POST_GET_FACE_AREA_RATIO_RESULT,
    // set face area ratio
    MSG_ID_POST_SET_FACE_AREA_RATIO_REQ,
    MSG_ID_POST_SET_FACE_AREA_RATIO_RESULT,
    // get body temperature param
    MSG_ID_POST_GET_BODY_TEMP_SNS_PARAM_REQ,
    MSG_ID_POST_GET_BODY_TEMP_SNS_PARAM_RESULT,
    // set body temperature param
    MSG_ID_POST_SET_BODY_TEMP_SNS_PARAM_REQ,
    MSG_ID_POST_SET_BODY_TEMP_SNS_PARAM_RESULT,
	// get door electric relay param
	MSG_ID_POST_GET_DOOR_ELECTRIC_RELAY_PARAM_REQ,
	MSG_ID_POST_GET_DOOR_ELECTRIC_RELAY_PARAM_RESULT,
	// set door electric relay param
	MSG_ID_POST_SET_DOOR_ELECTRIC_RELAY_PARAM_REQ,
	MSG_ID_POST_SET_DOOR_ELECTRIC_RELAY_PARAM_RESULT,


	MSG_ID_POST_HUIYUN_DEL_FACE_CMD,
	MSG_ID_POST_HUIYUN_MODIFY_FACE_BELONG_CMD,


	// GobiNet module control msg
	// lifan @2021.06.22
	MSG_ID_POST_ENABLE_GOBINET_MODULE_REQ,
	MSG_ID_POST_ENABLE_GOBINET_MODULE_RESULT,
	MSG_ID_POST_DISABLE_GOBINET_MODULE_REQ,
	MSG_ID_POST_DISABLE_GOBINET_MODULE_RESULT,
	MSG_ID_POST_QUERY_GOBINET_MODULE_STATUS_REQ,
	MSG_ID_POST_QUERY_GOBINET_MODULE_STATUS_RESULT,


	///////////////////////////////////////////////
	MSG_ID_POST_ASYNC_SESSION_MSG_TO_MISCDEV_REQ,
	MSG_ID_POST_ASYNC_SESSION_MSG_RESP,
	MSG_ID_POST_QUERY_FH_WIFI_QUIRK_REQ,
	MSG_ID_POST_QUERY_FH_WIFI_QUIRK_RESP,

	MSG_ID_POST_PLAY_DEV_IP_VOICE_PORMPT_CMD,
	
	MSG_ID_POST_CTRL_LIFT_MOVE_REQ,

	MSG_ID_POST_QUERY_CODEC_ENC_INFO_REQ,
	MSG_ID_POST_QUERY_CODEC_ENC_INFO_RESP,
	// add by lifan for json msg
	MSG_ID_POST_JSON_MSG_TO_XSIOT,
	MSG_ID_POST_JSON_MSG_TO_MC,
	MSG_ID_POST_JSON_MSG_TO_ALARMADAPTER,
	MSG_ID_POST_JSON_MSG_TO_CODEC,
	MSG_ID_POST_JSON_MSG_TO_MISCDEV,
	MSG_ID_POST_JSON_MSG_TO_NVT,
	MSG_ID_POST_JSON_MSG_TO_RTSPSERVER,	
	
	MSG_ID_POST_DAY_NIGHT_STATUS_CMD,
	MSG_ID_POST_HUIYUN_DEL_FACE_RESULT,
	MSG_ID_POST_HUIYUN_EDIT_FACE_RESULT,
	MSG_ID_POST_SNAPSHOT_RESULT,

	
	MSG_ID_BROADCAST_BASE		= 0x400000,		// broadcast msg
	MSG_ID_BROADCAST_MOTION_DETECT,
	MSG_ID_BROADCAST_MOTION_STOPED,
	MSG_ID_BROADCAST_WIFI_CONNECTED,
	MSG_ID_BROADCAST_WIFI_DISCONNECT,
	MSG_ID_BROADCAST_RESET,
	MSG_ID_BROADCAST_UPGRADE,
	MSG_ID_BROADCAST_EXPORT_CONFIG,
	MSG_ID_BROADCAST_IMPORT_CONFIG,
	MSG_ID_BROADCAST_UPGRADE_BEFORE_DOWNLOAD,
	MSG_ID_BROADCAST_UPGRAGE_BEFORE_WRITE_FLASH,
	MSG_ID_BROADCAST_VENC_PARAM_CHANGED,
	MSG_ID_BROADCAST_SYS_TIME_CHANGED,
	MSG_ID_BROADCAST_REBOOT,
	MSG_ID_BROADCAST_DEV_LIC_BURNED,
	MSG_ID_BROADCAST_DEV_UID_CHANGED,	
	MSG_ID_BROADCAST_TIME_SYNC_SUCCESSED,
	MSG_ID_BROADCAST_SDCARD_MOUNTED,
	MSG_ID_BROADCAST_SDCARD_UMOUNTED,
	MSG_ID_BROADCAST_MEIAN_PLATFORM_SERVER_CONFIG_CHANGED,
	MSG_ID_BROADCAST_MEIAN_ALARM_HOST_UPGRADE_START,   // MC --> AlarmAdapter
	MSG_ID_BROADCAST_MEIAN_ALARM_HOST_UPGRADE_SUCCESS, // AlarmAdapter --> broadcast
	MSG_ID_BROADCAST_MEIAN_BURN_DATA_CHANGED, // burn data
	MSG_ID_BROADCAST_MEIAN_ALARM_INFO,
	MSG_ID_BROADCAST_MEIAN_WIRELESS_DEV_MATCH_CODE_RESULT,
	MSG_ID_BROADCAST_MEIAN_MCU_VERSION_CMD,
	MSG_ID_BROADCAST_SD_CARD_IO_ERROR,
	MSG_ID_BROADCAST_ALARM_HOST_ARM_STATUS_UPDATED,
	MSG_ID_BROADCAST_MCU_UPGRADE_PROGRESS,
	MSG_ID_BROADCAST_MCU_STATUS,
	MSG_ID_BROADCAST_MCU_ZONE_STATUS,
	MSG_ID_BROADCAST_IN_MOTION,
	MSG_ID_BROADCAST_PIR_ALARM_MSG,
	MSG_ID_BROADCAST_OTA_UPGRADE_INFO_MSG,
	MSG_ID_BROADCAST_OTA_QUERY_FAILED_MSG,
	MSG_ID_BROADCAST_OTA_DOWNLOAD_RESULT_MSG,
	MSG_ID_BROADCAST_ETH_CONNECTED,
	MSG_ID_BROADCAST_ETH_DISCONNECT,	
	MSG_ID_BROADCAST_OTA_UPGRADE_INFO_MSGEX,
	MSG_ID_BROADCAST_OTA_QUERY_FAILED_MSGEX,
	MSG_ID_BROADCAST_OTA_DOWNLOAD_RESULT_MSGEX,
	MSG_ID_BROADCAST_MQTT_BROKEN_ONLINE_MSG,
	MSG_ID_BROADCAST_MQTT_BROKEN_OFFLINE_MSG,
	MSG_ID_BROADCAST_READ_QR_CODE_OR_RF_ID_INFO,
	MSG_ID_BROADCAST_QR_CODE_OR_RF_ID_CHECK_RESULT,
	MSG_ID_BROADCAST_BODY_DETECT_MSG,
	MSG_ID_BROADCAST_MCU_SWITCH_STATUS,
	MSG_ID_BROADCAST_FACE_COMPARE_RESULT_MSG,
	// THIS MSG COPY FROM NVR(Start). lifan @2021.03.24
	MSG_ID_BROADCAST_REMOVABLE_DISK_REJECT_MSG,
	MSG_ID_BROADCAST_REMOVABLE_DISK_INSERT_MSG,
	MSG_ID_BROADCAST_REMOVABLE_DISK_FORMAT_RESULT_MSG,
	// THIS MSG COPY FROM NVR(End). lifan @2021.03.24
	MSG_ID_BROADCAST_AI_DETECT_STOPED,

	MSG_ID_BROADCAST_NETWORK_CHANGED_BY_NVT_MSG,

	MSG_ID_BROADCAST_WIFI_ENABLE_MSG,

	MSG_ID_BROADCAST_SOS_TRIGGER_ACTIVE_MSG,

	MSG_ID_BROADCAST_UPDATE_ETH_STATUS_MSG,

    MSG_ID_BROADCAST_SET_WHITE_LIGHT_STATE,

	MSG_ID_BROADCAST_GET_TIME_FROM_NTP,
	
	MSG_ID_BROADCAST_CMS_PLAYBACK_SERVICE_EXIT_MSG,
	MSG_ID_BROADCAST_TIME_ZONE_CHANGED,

	MSG_ID_BROADCAST_YKM_PARSE_RESULT_MSG,
};



typedef struct{
	union{
		char CmdLineParam[512];
	};
}GOBINET_PARAM;

typedef enum{
	enum_gobinet_status_sim_absent = 100,
	
}ENUM_GOBINET_STATUS;

typedef struct{
	ENUM_GOBINET_STATUS enStatus;
	union{
		char data[64];
	};
}GOBINET_STATUS;

typedef struct{
	GOBINET_PARAM param;
}MSG_ENABLE_GOBINET_MODULE_REQ;
typedef struct{
	int32_t result;
}MSG_ENABLE_GOBINET_MODULE_RESP;
typedef struct{
	int32_t reserved;
}MSG_DISABLE_GOBINET_MODULE_REQ;
typedef struct{
	int32_t result;
}MSG_DISABLE_GOBINET_MODULE_RESP;

typedef struct{
	int32_t reserved;
}MSG_QUERY_GOBINET_STATUS_REQ;
typedef struct{
	int32_t result;
	GOBINET_STATUS gobinet;
}MSG_QUERY_GOBINET_STATUS_RESP;


typedef enum {
	JPEG_IMAGE_QUALITY_VERY_LOW = 0,	
	JPEG_IMAGE_QUALITY_LOW,
	JPEG_IMAGE_QUALITY_MID,
	JPEG_IMAGE_QUALITY_HIGH,
	JPEG_IMAGE_QUALITY_VERY_HIGH,
	
}JPEG_IMAGE_QUALITY_LEVEL;


enum {
	MSG_ERROR_NONE 				= 0,
	MSG_ERROR_INVALID_SIZE     	= 0x200000,
	MSG_ERROR_SET_VI_PARAM_FAILED,
	MSG_ERROR_SET_VENC_PARAM_FAILED,
	MSG_ERROR_CONNECT_NOT_EXIST,
	MSG_ERROR_SEND_MSG_ERROR,
	MSG_ERROR_TIMEOUT,
	MSG_ERROR_GET_VI_PARAM_FAILED,
	MSG_ERROR_GET_VENC_PARAM_FAILED,
	MSG_ERROR_GET_DEV_CAP_FAILED,
	MSG_ERROR_SNAPSHOT_FAILED,
	MSG_ERROR_GET_SNAPSHOT_IMAGE_QUALITY_FAILED,
	MSG_ERROR_SET_SNAPSHOT_IMAGE_QUALITY_FAILED,
	MSG_ERROR_GET_MOTION_DETECT_ATTR_FAILED,
	MSG_ERROR_SET_MOTION_DETECT_ATTR_FAILED,
	MSG_ERROR_GET_OSD_CONFIG_FAILED,
	MSG_ERROR_SET_OSD_CONFIG_FAILED,
	MSG_ERROR_GET_WIFI_INFO_FAILED,
	MSG_ERROR_SET_WIFI_ATTR_FAILED,
	MSG_ERROR_GET_NETWORK_STATUS_FAILED,
	MSG_ERROR_SET_NETWORK_ATTR_FAILED,
	MSG_ERROR_GET_CODEC_ENC_INFO_FAILED,
	MSG_ERROR_PLAYBACK_QUERY_FAILED,
	MSG_ERROR_PLAYBACK_START_FAILED,
	MSG_ERROR_PLAYBACK_STOP_FAILED,
	MSG_ERROR_GET_STORAGE_CONFIG_FAILED,
	MSG_ERROR_SET_STORAGE_CONFIG_FAILED,
	MSG_ERROR_GET_STORAGE_STATUS_FAILED,
	MSG_ERROR_GET_IRCUT_MODE_FAILED,
	MSG_ERROR_SET_IRCUT_MODE_FAILED,
	MSG_ERROR_VIDEO_CODEC_NOT_INITIALIZED,
	MSG_ERROR_TEST_IRCUT_OPEN_FAILED,
	MSG_ERROR_TEST_IRCUT_CLOSE_FAILED,
	MSG_ERROR_GET_AUDIO_CODEC_MISC_ATTR_FAILED,
	MSG_ERROR_SET_AUDIO_CODEC_MISC_ATTR_FAILED,
	MSG_ERROR_GET_NETWORK_ATTR_FAILED,
	MSG_ERROR_GET_MEIAN_PLATFORM_SERVER_CONFIG_FAILED,
	MSG_ERROR_GET_FISHEYE_CALIBRATION_PARAM_FAILED,
	MSG_ERROR_SET_FISHEYE_CALIBRATION_PARAM_FAILED,
	MSG_ERROR_GET_ALARM_HOST_ALL_PARAM_FAILED,
	MSG_ERROR_SET_ALARM_HOST_ARM_MODE_FAILED,
	MSG_ERROR_GET_ALARM_HOST_ARM_MODE_FAILED,
	MSG_ERROR_GET_MCU_VERSION_FAILED,
	MSG_ERROR_GET_ALARM_HOST_ARM_STATUS_FAILED,
	MSG_ERROR_GET_LANGUAGE_FAILED,
	MSG_ERROR_SET_LANGUAGE_FAILED,
	MSG_ERROR_GET_GMT_DIFF_FAILED,
	MSG_ERROR_SET_GMT_DIFF_FAILED,
	MSG_ERROR_GET_ALARM_DEVICES_FAILED,
	MSG_ERROR_GET_ALARM_ZONES_LINKAGE_FAILED,
	MSG_ERROR_SET_ALARM_ZONES_LINKAGE_FAILED,
	MSG_ERROR_ADD_ALARM_DEVICE_FAILED,
	MSG_ERROR_DEL_ALARM_DEVICE_FAILED,
	MSG_ERROR_CONTROL_SWITCH_FAILED,
	MSG_ERROR_QUERY_DOWNLOAD_FAILED,
	MSG_ERROR_GET_ARM_SCHEDULE_FAILED,
	MSG_ERROR_SET_ARM_SCHEDULE_FAILED,
	MSG_ERROR_SET_VENC_TYPE_FAILED,
	MSG_ERROR_GET_VENC_TYPE_FAILED,
	MSG_ERROR_GET_VOICE_PROMPT_ATTR_FAILED,
	MSG_ERROR_SET_VOICE_PROMPT_ATTR_FAILED,
	MSG_ERROR_GET_PIR_ENABLE_FAILED,
	MSG_ERROR_SET_PIR_ENABLE_FAILED,
	MSG_ERROR_PIR_NOT_SUPPORTED,
	MSG_ERROR_GET_ALARM_USER_PHONE,
	MSG_ERROR_SET_ALARM_USER_PHONE,
	MSG_ERROR_GET_SENSETIME_SDK_STATUS_FAILED,
	MSG_ERROR_QUERY_GUI_STATUS_FAILED,
	MSG_ERROR_QUERY_FB_STATUS_FAILED,
	MSG_ERROR_GET_MQTT_ADAPTER_PARAM_FAILED,
	MSG_ERROR_SET_MQTT_ADAPTER_PARAM_FAILED,
	MSG_ERROR_GET_DOOR_ELECTRIC_RELAY_PARAM_FAILED,
	MSG_ERROR_SET_DOOR_ELECTRIC_RELAY_PARAM_FAILED,
	MSG_ERROR_GET_ACCESS_VOICE_PROMPT_PARAM_FAILED,
	MSG_ERROR_SET_ACCESS_VOICE_PROMPT_PARAM_FAILED,
	MSG_ERROR_GET_AI_INPUT_IMAGE_SIZE_FAILED,
	MSG_ERROR_GET_RFID_READER_MODE_FAILED,
	MSG_ERROR_SET_RFID_READER_MODE_FAILED,
	MSG_ERROR_GET_ALL_RELAYS_CONFIG_FAILED,
	MSG_ERROR_AUDIO_CODEC_NOT_READY,
	MSG_ERROR_GUI_GET_SYS_LANG_FAILED,
	MSG_ERROR_GET_SOUND_PLAY_PARAM_FAILED,
	MSG_ERROR_SET_SOUND_PLAY_PARAM_FAILED,
	MSG_ERROR_SET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_FAILED,
	MSG_ERROR_GET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_FAILED,
	MSG_ERROR_MQTT_ADD_QR_CODE_FAILED,
	MSG_ERROR_GET_AI_RULES_PARAM_FAILED,
	MSG_ERROR_SET_AI_RULES_PARAM_FAILED,
	MSG_ERROR_GET_AI_AREAS_PARAM_FAILED,
	MSG_ERROR_SET_AI_AREAS_PARAM_FAILED,
	MSG_ERROR_GET_AI_ALARM_LINKAGE_PARAM_FAILED,
	MSG_ERROR_SET_AI_ALARM_LINKAGE_PARAM_FAILED,
	MSG_ERROR_GET_LINKAGE_SOUND_LIST_FAILED,
	MSG_ERROR_SET_LINKAGE_SOUND_LIST_FAILED,
	MSG_ERROR_GET_IRCUT_PARAM_FAILED,
	MSG_ERROR_SET_IRCUT_PARAM_FAILED,
	MSG_ERROR_GET_DAY_NIGHT_STATUS_FAILED,
	MSG_ERROR_GET_DB_FACE_COUNT_FAILED,
	MSG_ERROR_GET_FACE_COMPARE_THRESHOLD_FAILED,
	MSG_ERROR_SET_FACE_COMPARE_THRESHOLD_FAILED,
	MSG_ERROR_HUIYUN_SNAPSHOT_FAILED,
	MSG_ERROR_HUIYUN_GET_NET_STATUS_FAILED,
	MSG_ERROR_HUIYUN_GET_NET_ATTR_FAILED,
	MSG_ERROR_HUIYUN_SET_NET_ATTR_FAILED,
	MSG_ERROR_HUIYUN_GET_VIDEO_INPUT_PARAM_FAILED,
	MSG_ERROR_HUIYUN_SET_VIDEO_INPUT_PARAM_FAILED,
	MSG_ERROR_HUIYUN_GET_VIDEO_ENC_PARAM_FAILED,
	MSG_ERROR_HUIYUN_SET_VIDEO_ENC_PARAM_FAILED,
	MSG_ERROR_HUIYUN_GET_IRCUT_MODE_FAILED,
	MSG_ERROR_HUIYUN_SET_IRCUT_MODE_FAILED,
	MSG_ERROR_HUIYUN_GET_AUDIO_MISC_ATTR_FAILED,
	MSG_ERROR_HUIYUN_GET_GMT_DIFF_FAILED,
	MSG_ERROR_HUIYUN_SET_GMT_DIFF_FAILED,
	MSG_ERROR_HUIYUN_GET_MOTION_DETECT_PARAM_FAILED,
	MSG_ERROR_HUIYUN_SET_MOTION_DETECT_PARAM_FAILED,	
	MSG_ERROR_HUIYUN_GET_SIM_ICCID_FAILED,	
	MSG_ERROR_HUIYUN_GET_IMEI_FAILED,
	MSG_ERROR_HUIYUN_GET_4G_SIGNAL_QUALITY_FAILED,	
	MSG_ERROR_HUIYUN_GET_AI_AREAS_PARAM_FAILED,
	MSG_ERROR_HUIYUN_SET_AI_AREAS_PARAM_FAILED,
};



#define MSG_ERROR(e)  (-(e))




typedef struct{
	uint32_t 	id;		//msg id
	uint32_t 	token;		//msg token
	uint64_t	ts;			//msg send timestamp
	uint32_t 	bodySize;	//msg body size
	uint32_t    dataType;   // dataType;
	uint8_t 	Body[0];
}__attribute__((packed))LOCAL_MSG_t;

typedef struct{
	char name[64];
	uint32_t msgCount;
	uint32_t msgId[0];
}__attribute__((packed))MSG_BODY_CLIENT_REG_t;


typedef struct{
	char name[64];
}__attribute__((packed))MSG_BODY_CLIENT_UNREG_t;




//MSG_ID_SEND_TEST1
typedef struct{
	char sayHello[4096];
	time_t t;
}__attribute__((packed))MSG_BODY_TEST1_t;
//MSG_ID_RESP_TEST1
typedef struct{
	char sayResp[4096];
	time_t t;
}__attribute__((packed))MSG_BODY_TEST1_RESP_t;

//MSG_ID_SEND_TEST2
typedef struct{
	char sayBye[4096];
	time_t t;
}__attribute__((packed))MSG_BODY_TEST2_t;
//MSG_ID_RESP_TEST2
typedef struct{
	char sayByeBye[4096];
	time_t t;
}__attribute__((packed))MSG_BODY_TEST2_RESP_t;



typedef struct{
	uint32_t reserved;
}__attribute__((packed))MSG_GET_VI_PARAM;


typedef struct{
	int32_t result;
	VIDEO_INPUT_ATTR ViParam;
}__attribute__((packed))MSG_GET_VI_PARAM_RESULT;



typedef struct{
	VIDEO_INPUT_ATTR ViParam;
}__attribute__((packed))MSG_SET_VI_PARAM;


typedef struct{
	int32_t result;
}__attribute__((packed))MSG_SET_VI_PARAM_RESULT;



typedef struct{
	uint32_t reserved;
}__attribute__((packed))MSG_GET_VENC_PARAM;


typedef struct{
	int32_t result;
	VIDEO_ENC_ATTR VencParam;
}__attribute__((packed))MSG_GET_VENC_PARAM_RESULT;



typedef struct{
	VIDEO_ENC_ATTR VencParam;
}__attribute__((packed))MSG_SET_VENC_PARAM;


typedef struct{
	int32_t result;
}__attribute__((packed))MSG_SET_VENC_PARAM_RESULT;


typedef struct{
	uint32_t reserved;
}__attribute__((packed))MSG_GET_DEV_CAP_PARAM;


typedef struct{
	int32_t result;
	DEVICE_CAPACITY dev_cap;
}__attribute__((packed))MSG_GET_DEV_CAP_PARAM_RESULT;


typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_POST_FORCE_KEY_FRAME;

typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_POST_DEVICE_LICENSE_INVALID_MSG;


typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_POST_DEVICE_LICENSE_VALID_MSG;


typedef struct{
	char fileName[256];
}__attribute__((packed))MSG_SNAPSHOT_PARAM;


typedef struct{
	int32_t result;
}__attribute__((packed))MSG_SNAPSHOT_PARAM_RESULT;


typedef struct{
	uint32_t reserved;
}__attribute__((packed))MSG_GET_SNAPSHOT_QUALITY_PARAM;


typedef struct{
	int32_t result;
	int32_t quality; //JPEG_IMAGE_QUALITY_LEVEL
}__attribute__((packed))MSG_GET_SNAPSHOT_QUALITY_PARAM_RESULT;

typedef struct{
	int32_t quality; //JPEG_IMAGE_QUALITY_LEVEL
}__attribute__((packed))MSG_SET_SNAPSHOT_QUALITY_PARAM;


typedef struct{
	int32_t result;
}__attribute__((packed))MSG_SET_SNAPSHOT_QUALITY_PARAM_RESULT;


typedef struct{
	uint64_t timestamp;	// system start time;
	time_t t;			// system time;
}__attribute__((packed))MSG_BROADCAST_MOTION_DETECTED;

typedef struct{
	uint64_t timestamp;	// system start time;
	time_t t;			// system time;
}__attribute__((packed))MSG_BROADCAST_MOTION_STOPED;


typedef struct{
	int reseved;
}__attribute__((packed))MSG_BROADCAST_VENC_PARAM_CHANGED;


typedef struct{
	int enable ;
	int sensitivity;
}__attribute__((packed))MSG_SET_MOTION_DETECT_ATTR;

typedef struct{
	int32_t result;
}__attribute__((packed))MSG_SET_MOTION_DETECT_ATTR_RESULT;



typedef struct{
	int reserved;
}__attribute__((packed))MSG_GET_MOTION_DETECT_ATTR;

typedef struct{
	int32_t result;
	int enable ;
	int sensitivity;
}__attribute__((packed))MSG_GET_MOTION_DETECT_ATTR_RESULT;

typedef struct{
	int reserved;
}__attribute__((packed))MSG_GET_OSD_PARAM;









typedef struct{
	int32_t result;
	OSD_PARAM osd;
}__attribute__((packed))MSG_GET_OSD_PARAM_RESULT;


typedef struct{
	int reserved;
}__attribute__((packed))MSG_GET_VIDEO_ENC_INFO;

typedef struct{
	int32_t result;
	VideoCodecEncInfo info;
}__attribute__((packed))MSG_GET_VIDEO_ENC_INFO_RESULT;



typedef struct{
	OSD_PARAM osd;
}__attribute__((packed))MSG_SET_OSD_PARAM;


typedef struct{
	int32_t result;
}__attribute__((packed))MSG_SET_OSD_PARAM_RESULT;

typedef struct{
	uint32_t voice_prompt_type;
}__attribute__((packed))MSG_VOICE_PROMPT_PARAM;

typedef struct{
	uint32_t ip;
}__attribute__((packed))MSG_DEV_IP_VOICE_PROMPT_PARAM;


typedef struct{
	uint32_t reserved;
}__attribute__((packed))MSG_NOTIFY_CODEC_RESET;




typedef struct{
	WIFI_BASIC_ATTR attr;
}__attribute__((packed))MSG_SET_WIFI_BASIC_ATTR;

typedef struct{
	int32_t result;
}__attribute__((packed))MSG_SET_WIFI_BASIC_ATTR_RESULT;

typedef struct{
	int reserved;
}__attribute__((packed))MSG_GET_WIFI_INFO;


typedef struct{
	int32_t result;
	WIFI_INFO info;
}__attribute__((packed))MSG_GET_WIFI_INFO_RESULT;




typedef struct{
	NETWORK_ATTR attr;
}__attribute__((packed))MSG_SET_NETWORK_ATTR;

typedef struct{
	int32_t result;
}__attribute__((packed))MSG_SET_NETWORK_ATTR_RESULT;



typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_GET_NETWORK_ATTR;

typedef struct{
	int32_t result;
	NETWORK_ATTR attr;
}__attribute__((packed))MSG_GET_NETWORK_ATTR_RESULT;



typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_GET_NETWORK_STATUS;


typedef struct{
	int32_t result;
	NETWORK_STATUS status;
}__attribute__((packed))MSG_GET_NETWORK_STATUS_RESULT;

typedef struct{
	uint32_t reserved;
}__attribute__((packed))MSG_SET_RESET;



typedef struct{
	time_t start;
	time_t end;
	uint32_t recordType;
}__attribute__((packed))RECORD_RESULT_ITEM;

typedef struct{
	time_t start;
	time_t end;
	uint32_t recordTypeMap;
}__attribute__((packed))MSG_PLAYBACK_QUERY,CMD_PLAYBACK_QUERY;

#define MAX_QUERY_RESULT_ITEM_COUNT 512

typedef struct{
	int result;
	int record_count;
	RECORD_RESULT_ITEM item[MAX_QUERY_RESULT_ITEM_COUNT];
}__attribute__((packed))MSG_PLAYBACK_QUERY_RESULT,PLAYBACK_QUERY_RESULT,CMD_PLAYBACK_QUERY_RESULT;



typedef struct{
	time_t start;
}__attribute__((packed))MSG_PLAYBACK_START,CMD_PLAYBACK_START;




typedef struct{
	time_t result;
}__attribute__((packed))MSG_PLAYBACK_START_RESULT,CMD_PLAYBACK_START_RESULT;






typedef struct{
	int reserved;
}__attribute__((packed))MSG_PLAYBACK_STOP,CMD_PLAYBACK_STOP;




typedef struct{
	int result;
}__attribute__((packed))MSG_PLAYBACK_STOP_RESULT,CMD_PLAYBACK_STOP_RESULT;



typedef struct{
	uint32_t year;
	uint32_t month;
	uint32_t type;
	uint32_t reserved;
}__attribute__((packed))MSG_PLAYBACK_QUERY_DAYS;

typedef struct{
	int32_t result;
	uint32_t reserved;
	uint8_t days[32]; // 0 ,this day no  record,1,this day has record
}__attribute__((packed))MSG_PLAYBACK_QUERY_DAYS_RESULT;  // 8 Bytes align




typedef struct{
	uint32_t year;
	uint32_t month;
	uint32_t day;
	uint32_t type;
}__attribute__((packed))MSG_PLAYBACK_QUERY_ONE_DAY_REC_ITEM;


typedef struct{
	time_t start;
	time_t end;
	uint32_t size;
	uint32_t type;
}__attribute__((packed))QUERY_REC_ITEM;



#define MAX_ITEMS_ONE_DAY 256

typedef struct{
	uint32_t count;
	QUERY_REC_ITEM items[MAX_ITEMS_ONE_DAY];
}__attribute__((packed))QUERY_REC_ITEMS;





typedef struct{
	int32_t result;
	QUERY_REC_ITEMS items;
}__attribute__((packed))MSG_PLAYBACK_QUERY_ONE_DAY_REC_ITEM_RESULT;





typedef struct{
	uint8_t enable;
	uint8_t enableAudio;
	uint8_t recordType;			// ENUM_RECORD_TYPE_XXXX
	uint8_t recordStream;		// ENUM_STREAM_TYPE_XXXXX
}__attribute__((packed))STORAGE_CONFIG;


typedef struct{
	int reserved;
}__attribute__((packed))MSG_GET_STORAGE_CONFIG,CMD_GET_STORAGE_CONFIG;

typedef struct{
	int result;
	STORAGE_CONFIG config;
}__attribute__((packed))MSG_GET_STORAGE_CONFIG_RESULT,CMD_GET_STORAGE_CONFIG_RESULT;


typedef struct{
	STORAGE_CONFIG config;
}__attribute__((packed))MSG_SET_STORAGE_CONFIG,CMD_SET_STORAGE_CONFIG;

typedef struct{
	int result;
}__attribute__((packed))MSG_SET_STORAGE_CONFIG_RESULT,CMD_SET_STORAGE_CONFIG_RESULT;


typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_GET_STORAGE_STATUS;

typedef struct{
	int32_t result;
	SDCARD_STATUS status;
}__attribute__((packed))MSG_GET_STORAGE_STATUS_RESULT;


typedef struct{
	int32_t x_offset;
	int32_t y_offset;
	uint32_t width;
	uint32_t height;
}__attribute__((packed))FISH_EYE_CALIBRATION_PARAM;


typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_GET_FISH_EYE_CALIBRATION_PARAM;


typedef struct{
	int32_t result;
	int32_t reserved;
	FISH_EYE_CALIBRATION_PARAM calibration;
}__attribute__((packed))MSG_GET_FISH_EYE_CALIBRATION_PARAM_RESULT;



typedef struct{
	FISH_EYE_CALIBRATION_PARAM calibration;
}__attribute__((packed))MSG_SET_FISH_EYE_CALIBRATION_PARAM;


typedef struct{
	int32_t result;
}__attribute__((packed))MSG_SET_FISH_EYE_CALIBRATION_PARAM_RESULT;





///////////////////////////////////////////////////////////////////////////
//////////// BROADCAST MSG Data defintion             ////////////////////////////
///////////////////////////////////////////////////////////////////////////
typedef struct{
	int reserved;
}__attribute__((packed))MSG_BROADCAST_ETH_CONNECTED;

typedef struct{
	int reserved;
}__attribute__((packed))MSG_BROADCAST_ETH_DISCONNECTED;

typedef struct{
	int reserved;
}__attribute__((packed))MSG_BROADCAST_WIFI_CONNECTED;

typedef struct{
	int reserved;
}__attribute__((packed))MSG_BROADCAST_WIFI_DISCONNECTED;

typedef struct{
	int reserved;
}__attribute__((packed))MSG_BROADCAST_TIME_SYNC_SUCCESSED;

typedef struct{
    time_t s;
	int reserved;
}__attribute__((packed))MSG_BROADCAST_GET_TIME_FROM_NTP;

typedef struct{
	int reserved;
}__attribute__((packed))MSG_BROADCAST_RESET;

typedef struct{
	int reserved;
}__attribute__((packed))MSG_BROADCAST_BURN_DATA_CHANGED;

typedef struct{
	time_t t;
}__attribute__((packed))MSG_BROADCAST_PIR_ALARM_MSG;


typedef struct{
	char requester[64];
}__attribute__((packed))MSG_BROADCAST_UPGRADE_BEFORE_DOWNLOAD;

typedef struct{
	char requester[64];
	char firmware[256];
}__attribute__((packed))MSG_BROADCAST_UPGRADE_BEFORE_WRITE_FLASH;


typedef struct{
	DEVICE_TIME old;
	DEVICE_TIME now;
}__attribute__((packed))MSG_BROADCAST_SYS_TIME_CHANGED;

typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_BROADCAST_REBOOT;



typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_BROADCAST_SDCARD_MOUNTED;

typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_BROADCAST_SDCARD_UMOUNTED;


typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_BROADCAST_SDCARD_IO_ERROR;


typedef struct{
	int32_t status;// MEIAN_AREA_ARM_STATUS
}__attribute__((packed))MSG_BROADCAST_ALARM_HOST_ARM_STATUS_UPDATED;

typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_BROADCAST_DEV_LIC_BURNED;

typedef struct{
	uint32_t progress;
}__attribute__((packed))MSG_BROADCAST_MCU_UPGRADE_PROGRESS;


typedef struct{
	int32_t ircut_mode; // ENUM_IRCUT_MODE_XXX
	int32_t reserved;
}__attribute__((packed))MSG_SET_IRCUT_MODE;

typedef struct{
	int32_t result;
	int32_t reserved;
}__attribute__((packed))MSG_SET_IRCUT_MODE_RESULT;




typedef struct{
	int32_t reserved; 
	int32_t reserved2;
}__attribute__((packed))MSG_GET_IRCUT_MODE;

typedef struct{
	int32_t result; // ENUM_IRCUT_MODE_XXX
	int32_t ircut_mode;
}__attribute__((packed))MSG_GET_IRCUT_MODE_RESULT;


typedef struct{
	int32_t reserved; 
	int32_t reserved2;
}__attribute__((packed))MSG_TEST_IRCUT_OPEN;


typedef struct{
	int32_t reserved; 
	int32_t reserved2;
}__attribute__((packed))MSG_TEST_IRCUT_CLOSE;

typedef struct{
	int32_t result; 
	int32_t reserved2;
}__attribute__((packed))MSG_TEST_IRCUT_OPEN_RESULT;


typedef struct{
	int32_t result; 
	int32_t reserved2;
}__attribute__((packed))MSG_TEST_IRCUT_CLOSE_RESULT;




typedef struct{
	uint32_t nUidSize;
	uint32_t reserved;
	uint8_t uid[128];
}__attribute__((packed))MSG_BROADCAST_DEV_UID_CHANGED;



typedef struct{
	AUDIO_MISC_ATTR attr;
}__attribute__((packed))MSG_SET_AUDIO_MISC_ATTR;



typedef struct{
	int32_t reserved; 
	int32_t reserved2;
}__attribute__((packed))MSG_GET_AUDIO_MISC_ATTR;




typedef struct{
	int32_t result; 
	int32_t reserved2;
	AUDIO_MISC_ATTR attr;
}__attribute__((packed))MSG_GET_AUDIO_MISC_ATTR_RESULT;




typedef struct{
	time_t t;
	int32_t reserved;
}__attribute__((packed))POST_MSG_SET_SYSTEM_GMT_TIME;







typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_POST_WIRELESS_DEVICE_MATCH_CODE_START;

typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_POST_WIRELESS_DEVICE_MATCH_CODE_STOP;





typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_GET_MCU_VERSION;

typedef struct{
	int32_t result;
	char version[128];
}__attribute__((packed))MSG_GET_MCU_VERSION_RESULT;


typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_GET_ALARM_HOST_ARM_STATUS;

typedef struct{
	int32_t result;
	int32_t status;// MEIAN_AREA_ARM_STATUS
}__attribute__((packed))MSG_GET_ALARM_HOST_ARM_STATUS_RESULT;



typedef struct{
	uint32_t language;
}__attribute__((packed))MSG_SET_LANGUAGE_REQ;


typedef struct{
	int32_t result;
}__attribute__((packed))MSG_SET_LANGUAGE_RESULT;


typedef struct{
	uint32_t reserved;
}__attribute__((packed))MSG_GET_LANGUAGE_REQ;


typedef struct{
	int32_t result;
	uint32_t language;
}__attribute__((packed))MSG_GET_LANGUAGE_RESULT;









typedef struct{
	int32_t gmt_diff;
}__attribute__((packed))MSG_SET_GMT_DIFF_REQ;


typedef struct{
	int32_t result;
}__attribute__((packed))MSG_SET_GMT_DIFF_RESULT;


typedef struct{
	uint32_t reserved;
}__attribute__((packed))MSG_GET_GMT_DIFF_REQ;


typedef struct{
	int32_t result;
	int32_t gmt_diff;
}__attribute__((packed))MSG_GET_GMT_DIFF_RESULT;



typedef struct{
	int index;		// stream index.ENUM_STREAM_TYPE_MAIN/ENUM_STREAM_TYPE_SUB
	int frame_rate; // MSC313E : mainstream [8,20] ,substream[8,15]
}NVR_REQ_FRAME_RATE_PARAM;



typedef struct{
	int32_t reserved;
}MSG_GET_VENC_TYPE_REQ;

typedef struct{
	int32_t result;
	uint32_t codec_id;
}MSG_GET_VENC_TYPE_RESULT;



typedef struct{
	uint32_t codec_id;
}MSG_SET_VENC_TYPE_REQ;

typedef struct{
	int32_t result;
}MSG_SET_VENC_TYPE_RESULT;





typedef struct{
	int32_t reserved;
}MSG_GET_VOICE_PROMPT_ATTR_REQ;

typedef struct{
	int32_t result;
	uint32_t enable;
}MSG_GET_VOICE_PROMPT_ATTR_RESULT;



typedef struct{
	uint32_t enable;
}MSG_SET_VOICE_PROMPT_ATTR_REQ;

typedef struct{
	int32_t result;
}MSG_SET_VOICE_PROMPT_ATTR_RESULT;




typedef struct{
	int32_t reserved;
}MSG_GET_PIR_ENABLE_REQ;

typedef struct{
	int32_t result;
	uint32_t enable;
}MSG_GET_PIR_ENABLE_RESULT;



typedef struct{
	uint32_t enable;
}MSG_SET_PIR_ENABLE_REQ;

typedef struct{
	int32_t result;
}MSG_SET_PIR_ENABLE_RESULT;


typedef struct{
	int channel;
}__attribute__((packed))MSG_POST_FIRE_SMOKE_BOMB;


typedef struct{
	int32_t reserved;
}MSG_POST_CODEC_NOTIFY_GUI_EXIT_MSG;

typedef struct{
	int32_t reserved;
}MSG_POST_CODEC_NOTIFY_GUI_FB_WILL_START_MSG;



typedef struct{
	uint8_t  workMode;      //bit 0 迎宾提示 bit 1 预警提示 bit2 报警提示
	uint8_t  reserve[3];    //预留
	uint8_t  CID[4];        //警情ID
	uint32_t alarmStatus;  //0 1分区布撤防状态( 01: 撤防  10 在家布防  11 外出布防)
}__attribute__((packed))MSG_POST_SET_SOUND_LIGHT_ALARM;


typedef enum{
	enum_face_type_white_list 	= 0,
	enum_face_type_black_list,
}ENUM_FACE_TYPE;

typedef enum{
	enum_add_face_result_successfully			= 0,
	enum_add_face_result_req_invalid 			= -1,
	enum_add_face_result_msg_parse_failed 		= -2,	
	enum_add_face_result_msg_sex_type_invalid 	= -3,
	enum_add_face_result_msg_sensetime_sdk_error= -4,
	enum_add_face_result_face_existed 			= -5,
	enum_add_face_result_face_db_error 			= -6,
	enum_add_face_result_sdk_not_ready			= -7,
}ENUM_ADD_FACE_RESULT;



typedef enum{
	enum_del_face_result_successfully			= 0,
	enum_del_face_result_face_id_not_exist			= -1,
	enum_del_face_result_sdk_not_ready				= -2,
	enum_del_face_result_face_type_invalid		= -3,
}ENUM_DEL_FACE_RESULT;



typedef enum{
	enum_edit_face_result_successfully			= 0,
	enum_edit_face_result_face_not_exist		= -1,
	enum_edit_face_result_param_invalid			= -2,
	enum_edit_face_result_sdk_not_ready			= -3,
	enum_edit_face_result_face_type_invalid		= -4,
}ENUM_EDIT_FACE_RESULT;

typedef struct{
	ENUM_FACE_TYPE enFaceType;
	char strFaceReqFile[256];
	uint64_t token;
	uint32_t sid;
}__attribute__((packed))MSG_POST_ADD_FACE,MSG_POST_EDIT_FACE;

typedef struct{
	int32_t result; // ENUM_ADD_FACE_RESULT,ENUM_EDIT_FACE_RESULT
	uint32_t sid;
	uint64_t token;
}__attribute__((packed))MSG_POST_ADD_FACE_RESULT,MSG_POST_EDIT_FACE_RESULT;

typedef struct{
	int32_t result; // ENUM_IMPORT_FACE_DB_RESULT
	uint32_t sid;
	uint64_t token;
}__attribute__((packed))MSG_POST_IMPORT_FACE_DB_RESULT;

typedef struct{
	int32_t result; // ENUM_DEL_FACE_RESULT
	uint32_t sid;
	uint64_t token;
}__attribute__((packed))MSG_POST_DEL_FACE_RESULT;

typedef struct{
	ENUM_FACE_TYPE enFaceType;
	uint32_t faceid;
	uint64_t token;
	uint32_t sid;
}__attribute__((packed))MSG_POST_DEL_FACE;


typedef struct{
	ENUM_FACE_TYPE enFaceType;
	uint64_t token;
}__attribute__((packed))MSG_POST_GET_FACE_LIST;

typedef struct{}MSG_POST_EXPORT_FACE_DB;
typedef struct{}MSG_POST_IMPORT_FACE_DB;

typedef enum{
	enum_sensetime_sdk_status_ok			= 0,
	enum_sensetime_sdk_wait_initialize		= -1,
	enum_sensetime_sdk_load_license_failed 	= -2,
	enum_sensetime_sdk_create_layers_failed = -3,
	enum_sensetime_sdk_deinitialize			= -4,
}ENUM_SENSETIME_SDK_STATUS;

typedef struct{
	uint32_t reserved;
}MSG_GET_SENSETIME_SDK_STATUS_REQ;
typedef struct{
	int32_t result;
	ENUM_SENSETIME_SDK_STATUS status;
}MSG_GET_SENSETIME_SDK_STATUS_RESULT;

typedef enum{
	enum_face_db_import_result_ok 					= 0,
	enum_face_db_import_result_exceed_max_size 		= -1,
	enum_face_db_import_result_socket_error			= -2,
	enum_face_db_import_result_start_import_failed	= -3,
	enum_face_db_import_result_crc_check_failed		= -4,
	enum_face_db_import_result_sensetime_sdk_not_ready		= -5,
	enum_face_db_import_result_replace_failed		= -6,
}FACE_DB_IMPORT_RESULT,ENUM_IMPORT_FACE_DB_RESULT;



typedef struct{
	uint32_t crc_val;
	uint32_t sid;
	uint64_t token;
	char file_path[128];
}MSG_POST_CODEC_IMPORT_FACE_DB_FILE_READY_REQ;




typedef enum{
	enum_gui_status_wait_fb	= 0,
	enum_gui_status_in_fb,
	enum_gui_status_exit_fb,
}ENUM_GUI_STATUS;

typedef struct{
	int32_t reserved;
}MSG_QUERY_GUI_STATUS_REQ;
typedef struct{
	int32_t result;
	ENUM_GUI_STATUS enStat;
}MSG_QUERY_GUI_STATUS_RESULT;

typedef struct{
	int32_t reserved;
}MSG_QUERY_FB_STATUS_REQ;
typedef struct{
	int32_t result;
	int32_t ready;
}MSG_QUERY_FB_STATUS_RESULT;


typedef struct{
	char userId[256];
	time_t t;
	uint32_t accessMode;
}MSG_PUSH_ACCESS_RECORD;


typedef enum{
	enum_add_request_type_mqtt = 0,
	enum_add_request_type_mc,
	enum_add_request_type_gui,   // add by local gui ,lifan @2021.03.22
}ENUM_ADD_REQUEST_TYPE;


typedef struct{
	uint32_t sid;
	uint32_t reserved;
	uint64_t token;
}MC_INFO;

typedef struct{
	char userId[256];
	char jpegPath[256];
	union{
		char token[128];
		MC_INFO mc_info;
	};
	uint32_t isAddFace : 1;
	uint32_t isReturnFaceFeature : 1;
	uint32_t enAddReqType:6; //ENUM_ADD_REQUEST_TYPE
	uint32_t reserved :8;
	uint32_t reserved_floor:16;
}MSG_ADD_FACE_WITH_JPEG;


typedef struct{
	char userId[256];
	union{
	char token[128];
		MC_INFO mc_info;
	};
	int errorCode;

	uint32_t isAddFace : 1;
	uint32_t isReturnFaceFeature : 1;
	uint32_t enAddReqType:6; //ENUM_ADD_REQUEST_TYPE
	uint32_t reserved :8;
	uint32_t reserved_floor:16;
	float faceQuality;
	float feature[256];
}MSG_ADD_FACE_WITH_JPEG_RESULT;

typedef enum{
	enum_access_ctrl_error_code_success			= 0,
	enum_access_ctrl_error_code_download_face_pic_timeout = -1,
	enum_access_ctrl_error_code_download_face_pic_failed = -2,
	enum_access_ctrl_error_code_user_id_not_exist = -3,
	enum_access_ctrl_error_code_param_invalid = -4,
	enum_access_ctrl_error_code_register_failed = -5,
	enum_access_ctrl_error_code_user_id_had_existed = -6,
	enum_access_ctrl_error_code_face_invalid = -7,
	enum_access_ctrl_error_code_inner_error = -8,
	enum_access_ctrl_error_code_jpeg_decode_failed = -9,
	enum_access_ctrl_error_code_add_face_failed = -10,
	enum_access_ctrl_error_code_add_face_pic_not_feature = -11,
	enum_access_ctrl_error_code_query_offline_access_record_failed = -12,
	enum_access_ctrl_error_code_busy = -13,
	enum_access_ctrl_error_code_rf_id_not_exist = -14,
	enum_access_ctrl_error_code_rf_id_existed = -15,
	enum_access_ctrl_error_code_add_rf_id_failed = -16,
	enum_access_ctrl_error_code_rm_rf_id_failed = -16,
	enum_access_ctrl_error_code_get_rf_id_reader_mode_failed = -17,
	enum_access_ctrl_error_code_set_rf_id_reader_mode_failed = -18,
	enum_access_ctrl_error_code_add_face_operation_not_support = -19,
}ENUM_ACCESS_CONTROLLER_ERROR_CODE;









typedef struct{

}SENSETIME_SDK_INIT_STATUS;




typedef struct{
	char token[128];
	time_t start;
	time_t end;
}MSG_QUERY_OFFLINE_ACCESS_RECORD_REQ;
typedef struct{
	char 	 token[128];
	int      errorCode;
	uint32_t totalCount;
	uint32_t sliceIndex;
	uint32_t sliceCount;
	uint32_t playloadSize;
	uint8_t  playload[4096 - sizeof(uint32_t) - sizeof(uint32_t) - sizeof(uint32_t) - sizeof(uint32_t) - sizeof(uint32_t) - 128];
}MSG_QUERY_OFFLINE_ACCESS_RECORD_RESP;



typedef struct{
	uint32_t reserved;
}MSG_QUERY_AI_MODULE_READY_REQ;
typedef struct{
	uint32_t ready;
}MSG_QUERY_AI_MODULE_READY_RESP;



typedef struct{
	uint32_t reserved;
}MSG_BROADCAST_MQTT_BROKEN_ONLINE_MSG;

typedef struct{
	uint32_t reserved;
}MSG_BROADCAST_MQTT_BROKEN_OFFLINE_MSG;


typedef struct{
	uint32_t reserved;
}MSG_QUERY_MQTT_BROKER_STATUS;

/*

<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="14">
<m_stConfig class_id="0" tracking_level="0" version="0">
        <host>61.149.254.174</host>
        <port>3883</port>
        <enable_auth>1</enable_auth>
        <user>admin</user>
        <password>sun@way$land</password>
        <factoryId>abcd</factoryId>
        <deviceType>0</deviceType>
        <heartBeatInterval>15</heartBeatInterval>
        <devicePositionDesc>shenzhen</devicePositionDesc>
        <devicePostitonCode>00000000000</devicePostitonCode>
        <flag1></flag1>
        <flag2></flag2>
        <flag3></flag3>
        <flag4></flag4>
</m_stConfig>
</boost_serialization>


<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="14">
<m_stConfig class_id="0" tracking_level="0" version="0">
        <topic>jinmao</topic>
        <flag1></flag1>
        <flag2></flag2>
        <flag3></flag3>
        <flag4></flag4>
</m_stConfig>
</boost_serialization>

<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="14">
<m_stConfig class_id="0" tracking_level="0" version="0">
        <topics class_id="1" tracking_level="0" version="0">
                <count>1</count>
                <item_version>0</item_version>
                <item>BJ-WJJMF</item>
        </topics>
        <flag1></flag1>
        <flag2></flag2>
        <flag3></flag3>
        <flag4></flag4>
</m_stConfig>
</boost_serialization>


*/

typedef struct{
	char host[256];
	uint32_t port;
	uint32_t enable_auth;
	char user[128];
	char password[128];
	char factoryId[128];
	uint32_t deviceType;
	uint32_t heartBeatInterval;
	char devicePositionDesc[512];
	char devicePostitonCode[128];
}__attribute__((packed))MQTT_ADAPTER_BASE_PARAM;



typedef struct{
	char topic[128];
}__attribute__((packed))MQTT_ADAPTER_PUBLISH_TOPIC_PARAM;

typedef struct{
	char topic[128];
}__attribute__((packed))MQTT_ADAPTER_SUBSCRIBE_TOPIC_PARAM;


typedef struct{
	MQTT_ADAPTER_BASE_PARAM base;
	MQTT_ADAPTER_PUBLISH_TOPIC_PARAM publish;
	MQTT_ADAPTER_SUBSCRIBE_TOPIC_PARAM subscribe;
}__attribute__((packed))MQTT_ADAPTER_PARAM;


typedef struct{
	uint32_t reserved;
}MSG_GET_MQTT_ADAPTER_PARAM_REQ;
typedef struct{
	int result;
	MQTT_ADAPTER_PARAM param;
}MSG_GET_MQTT_ADAPTER_PARAM_RESP;
typedef struct{
	MQTT_ADAPTER_PARAM param;
}MSG_SET_MQTT_ADAPTER_PARAM_REQ;
typedef struct{
	int result;
}MSG_SET_MQTT_ADAPTER_PARAM_RESP;


typedef struct{
	uint32_t reverse;
	uint32_t keepTime;
}DOOR_ELECTRIC_RELAY_PARAM;


typedef struct{
	uint32_t reserved;
}MSG_GET_DOOR_ELECTRIC_RELAY_PARAM_REQ,MSG_POST_GET_DOOR_ELECTRIC_RELAY_PARAM_REQ;
typedef struct{
	int result;
	DOOR_ELECTRIC_RELAY_PARAM param;
}MSG_GET_DOOR_ELECTRIC_RELAY_PARAM_RESP,MSG_POST_GET_DOOR_ELECTRIC_RELAY_PARAM_RESP;
typedef struct{
	DOOR_ELECTRIC_RELAY_PARAM param;
}MSG_SET_DOOR_ELECTRIC_RELAY_PARAM_REQ,MSG_POST_SET_DOOR_ELECTRIC_RELAY_PARAM_REQ;
typedef struct{
	int result;
}MSG_SET_DOOR_ELECTRIC_RELAY_PARAM_RESP,MSG_POST_SET_DOOR_ELECTRIC_RELAY_PARAM_RESP;



typedef struct{
	uint32_t WLVoicePromptFileSize;
	uint32_t BLVoicePromptFileSize;
	uint32_t StrangerVoicePromptFileSize;
	uint32_t reserved;
}USER_VOICE_PROMPT_INFO;


typedef struct{
	uint32_t enable;
	uint32_t whitelist;
	uint32_t blacklist;
	uint32_t stranger;
	union{
		uint32_t padding[4];
		USER_VOICE_PROMPT_INFO user;
	};
}ACCESS_VOICE_PROMPT_PARAM;


typedef struct{
	uint32_t reserved;
}MSG_GET_ACCESS_VOICE_PROMPT_PARAM_REQ;
typedef struct{
	int result;
	ACCESS_VOICE_PROMPT_PARAM param;
}MSG_GET_ACCESS_VOICE_PROMPT_PARAM_RESP;
typedef struct{
	ACCESS_VOICE_PROMPT_PARAM param;
}MSG_SET_ACCESS_VOICE_PROMPT_PARAM_REQ;
typedef struct{
	int result;
}MSG_SET_ACCESS_VOICE_PROMPT_PARAM_RESP;




typedef struct{
	uint32_t w;
	uint32_t h;
}AI_INPUT_IMAGE_SIZE;

typedef struct{
	uint32_t reserved;
}MSG_GET_AI_INPUT_IMAGE_SIZE_REQ;
typedef struct{
	int result;
	AI_INPUT_IMAGE_SIZE size;
}MSG_GET_AI_INPUT_IMAGE_SIZE_RESP;





typedef struct{
	ENUM_ACCESS_MODE enAccessMode;
	union{
		char qrCode[512];
		char rfId[128];
	};
}MSG_BROADCAST_READ_QRCODE_OR_RFID_DATA;



typedef struct{
	int32_t result;  // < 0 : get error ; 0 : check failed ; 1 : check successfully
	MSG_BROADCAST_READ_QRCODE_OR_RFID_DATA data;
}MSG_BROADCAST_QRCODE_OR_RFID_DATA_CHECK_RESULT;





typedef enum{
	enum_rfid_reader_mode_base		= 0,
	enum_rfid_reader_mode_normal	= enum_rfid_reader_mode_base,
	enum_rfid_reader_mode_auto_add,
	enum_rfid_reader_mode_report_card_number,
	enum_rfid_reader_mode_butt,
}ENUM_RFID_READER_MODE;


typedef struct{
	ENUM_RFID_READER_MODE enMode;
}MSG_SET_RFID_READER_MODE_REQ;

typedef struct{
	int32_t result;
}MSG_SET_RFID_READER_MODE_RESP;

typedef struct{
	uint32_t reserved;
}MSG_GET_RFID_READER_MODE_REQ;

typedef struct{
	int32_t result;
	ENUM_RFID_READER_MODE enMode;
}MSG_GET_RFID_READER_MODE_RESP;

typedef struct{
	uint32_t sound;
	uint32_t interval:8;
	uint32_t enable:1;
	uint32_t reserved:23;
}__attribute__((packed))ALARM_SOUND_PLAY_PARAM;



typedef struct{
	uint32_t reserved;
	uint32_t reserved2;
}__attribute__((packed))MSG_GET_SOUND_PLAY_PARAM_REQ;
typedef struct{
	int32_t result;
	uint32_t count;
	ALARM_SOUND_PLAY_PARAM sound[0];
}__attribute__((packed))MSG_GET_SOUND_PLAY_PARAM_RESP;
typedef struct{
	uint32_t count;
	ALARM_SOUND_PLAY_PARAM sound[0];
}__attribute__((packed))MSG_SET_SOUND_PLAY_PARAM_REQ;
typedef struct{
	int32_t result;
}__attribute__((packed))MSG_SET_SOUND_PLAY_PARAM_RESP;




typedef struct{
	char token[128];
	char userId[128];
}MSG_JINMAO_DELETE_USER_REQ;
typedef struct{
	int32_t errorCode;
	char token[128];
	char userId[128];
}MSG_JINMAO_DELETE_USER_RESP;




typedef enum{
	enum_rfid_operation_owner_misc_dev = 0,
	enum_rfid_operation_owner_mc = 1,
}ENUM_RFID_OPERATION_OWNER_TYPE;



typedef struct{
	char content[128];
}RFID_ADD_REQ;
typedef struct{
	char content[128];
}RFID_DEL_REQ;

typedef struct{
	RFID_ADD_REQ add;
	uint32_t who; //ENUM_RFID_OPERATION_OWNER_TYPE
	uint32_t sid; // just used in MainController process...
	uint64_t token;//just used in MainController process...
}MSG_RFID_ADD_REQ;

typedef struct{
	int32_t result;
	MSG_RFID_ADD_REQ req;
}MSG_RFID_ADD_RESP;

typedef struct{
	RFID_DEL_REQ del;
	uint32_t who;//ENUM_RFID_OPERATION_OWNER_TYPE
	uint32_t sid; // just used in MainController process...
	uint64_t token;//just used in MainController process...
}MSG_RFID_DEL_REQ;

typedef struct{
	int32_t result;
	MSG_RFID_DEL_REQ req;
}MSG_RFID_DEL_RESP;

typedef struct{
	char content[128];
}MSG_REPORT_RFID_REPORT_REQ;


typedef struct{
	float fLeft;    // fLeft = (float) left/width;
	float fTop;		// fTop  = (float) top /height;
	float fRight;  // fRight = (float) right/width;
	float fBottom; // fBottom  = (float) bottom /height;
}BODY_POSITION_ITEM;

#define CONFIG_MAX_DETECT_BODY_COUNT 16
typedef struct{
	BODY_POSITION_ITEM bodys[CONFIG_MAX_DETECT_BODY_COUNT];
	uint32_t count;
}MSG_BROADCAST_BODY_DETECT_MSG;

typedef struct{
	uint32_t faceType; //ENUM_FACE_TYPE ; white list or black list...
	char name[256 - sizeof(uint32_t)];
}MSG_BROADCAST_FACE_COMPARE_RESULT;

typedef struct{
	uint32_t powerOn;
}MSG_WIFI_POWER_CTRL_REQ;

typedef struct{
	uint64_t token;
	uint32_t sid;
}CLEAR_FACE_DB_REQ;

typedef struct{
	CLEAR_FACE_DB_REQ req;
}MSG_CLEAR_FACE_DB_REQ;
typedef struct{
	int32_t result;
	CLEAR_FACE_DB_REQ req;
}MSG_CLEAR_FACE_DB_RESP;



typedef struct{
	uint32_t reserved;
	uint32_t reserved2;
}MSG_GET_SYSTEM_LANG_REQ;
typedef struct{
	uint32_t result;
	uint32_t lang;
}MSG_GET_SYSTEM_LANG_RESP;





typedef struct{
	int ctrlMode;		// ENUM_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_MODE
	int brightness;		// [0,100];
}DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM;




typedef struct{
	uint32_t reserved;
}MSG_GET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_REQ,MSG_POST_GET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_REQ;
typedef struct{
	int32_t result;
	uint32_t reserved;
	DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM param;
}MSG_GET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_RESP,MSG_POST_GET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_RESP;

typedef struct{
	DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM param;
}MSG_SET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_REQ,MSG_POST_SET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_REQ;
typedef struct{
	int32_t result;
}MSG_SET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_RESP,MSG_POST_SET_DOUBLE_SENSOR_WHITE_LIGHT_CTRL_PARAM_RESP;

typedef struct{
	uint32_t reserved;
}MSG_POST_QUERY_BODY_TEMPERATURE_REQ;


typedef struct{
	float fMaxBodyTemperature;
	union{
		struct{
			uint32_t uploadAbnormalTempMsg : 1;
			uint32_t accessDeny : 1;
			uint32_t soundWarnig : 1;
			uint32_t displayAbnormalTempMsg : 1;
			uint32_t reserved : 28;
		}bit;

		uint32_t map;

	};
}BODY_TEMPERATURE_SENSOR_PARAM;

typedef struct{
	float body_temperature;
	float env_temperature;
	BODY_TEMPERATURE_SENSOR_PARAM config;
}BODY_TEMPERATURE_QUERY_RESULT;

typedef struct{
	BODY_TEMPERATURE_QUERY_RESULT result;
}MSG_POST_QUERY_BODY_TEMPERATURE_RESP;




typedef struct{
	uint32_t refCnt;
	uint32_t stayTime;
	int32_t  floor;// add by lifan for jinmao project,2021.09.02
	char     qrCodeContent[0];
}__attribute__((packed))MSG_MQTT_ADD_QR_CODE_REQ;

typedef struct{
	int32_t  result;
	uint32_t reserved;
}__attribute__((packed))MSG_MQTT_ADD_QR_CODE_RESP;




typedef struct{
	float fMax;
	float fMin;
}FACE_AREA_RATIO_INFO;







typedef struct{
	uint32_t reserved;
}MSG_GET_FACE_AREA_RATIO_REQ,MSG_POST_GET_FACE_AREA_RATIO_REQ;
typedef struct{
	int32_t result;
	uint32_t reserved;
	FACE_AREA_RATIO_INFO param;
}MSG_GET_FACE_AREA_RATIO_RESP,MSG_POST_GET_FACE_AREA_RATIO_RESP;

typedef struct{
	FACE_AREA_RATIO_INFO param;
}MSG_SET_FACE_AREA_RATIO_REQ,MSG_POST_SET_FACE_AREA_RATIO_REQ;
typedef struct{
	int32_t result;
}MSG_SET_FACE_AREA_RATIO_RESP,MSG_POST_SET_FACE_AREA_RATIO_RESP;




typedef struct{
	uint32_t reserved;
}MSG_GET_BODY_TEMP_SNS_PARAM_REQ,MSG_POST_GET_BODY_TEMP_SNS_PARAM_REQ;
typedef struct{
	int32_t result;
	uint32_t reserved;
	BODY_TEMPERATURE_SENSOR_PARAM param;
}MSG_GET_BODY_TEMP_SNS_PARAM_RESP,MSG_POST_GET_BODY_TEMP_SNS_PARAM_RESP;

typedef struct{
	BODY_TEMPERATURE_SENSOR_PARAM param;
}MSG_SET_BODY_TEMP_SNS_PARAM_REQ,MSG_POST_SET_BODY_TEMP_SNS_PARAM_REQ;
typedef struct{
	int32_t result;
}MSG_SET_BODY_TEMP_SNS_PARAM_RESP,MSG_POST_SET_BODY_TEMP_SNS_PARAM_RESP;



typedef enum {
	MIC_SPEAKER_CTRL_MODE_0=0x00, // 0x00:IPC AO->Speaker&GSM AI, MIC->IPC, Amplifier Off
	MIC_SPEAKER_CTRL_MODE_1=0x01, // 0x01:IPC AO->Speaker&GSM AI, MIC->IPC, Amplifier On
	MIC_SPEAKER_CTRL_MODE_2=0x02, // 0x02:IPC AO->Speaker, MIC->GSM, Amplifier Off
	MIC_SPEAKER_CTRL_MODE_3=0x03, // 0x03:IPC AO->Speaker, MIC->GSM, Amplifier On
	MIC_SPEAKER_CTRL_MODE_4=0x04, // 0x04:IPC AO->GSM AI, GSM AO->Speaker, MIC->IPC, Amplifier Off
	MIC_SPEAKER_CTRL_MODE_5=0x05, // 0x05:IPC AO->GSM AI, GSM AO->Speaker, MIC->IPC, Amplifier On
	MIC_SPEAKER_CTRL_MODE_6=0x06, // 0x06:GSM AO->Speaker, MIC->GSM, Amplifier Off
	MIC_SPEAKER_CTRL_MODE_7=0x07, // 0x07:GSM AO->Speaker, MIC->GSM, Amplifier On
}MIC_SPEAKER_CTRL_MODE;

typedef struct{
	uint32_t nSwitch;
}MSG_MIC_SPEAKER_CTRL_REQ;

typedef enum{
	ENUM_PTZ_CMD_STOP 	      = 0x00,
	ENUM_PTZ_CMD_LEFT		  = 0x01,
	ENUM_PTZ_CMD_RIGHT		  = 0x02,
	ENUM_PTZ_CMD_UP 		  = 0x03,
	ENUM_PTZ_CMD_DOWN		  = 0x04,
	ENUM_PTZ_CMD_LEFT_UP	  = 0x05,
	ENUM_PTZ_CMD_LEFT_DOWN	  = 0x06,
	ENUM_PTZ_CMD_RIGHT_UP	  = 0x07,
	ENUM_PTZ_CMD_RIGHT_DOWN	  = 0x08,

	ENUM_PTZ_CMD_PRESET_CALL  = 0x10,
	ENUM_PTZ_CMD_PRESET_SET   = 0x11,
	ENUM_PTZ_CMD_PRESET_CLEAR = 0x12,
	
	ENUM_PTZ_CMD_FOCUS_FAR    = 0x20,
	ENUM_PTZ_CMD_FOCUS_NEAR   = 0x21,
	ENUM_PTZ_CMD_IRIS_OPEN    = 0x22,
	ENUM_PTZ_CMD_IRIS_CLOSE   = 0x23,
	ENUM_PTZ_CMD_ZOOM_IN      = 0x24,
	ENUM_PTZ_CMD_ZOOM_OUT     = 0x25,
}ENUM_PTZ_CMD;

typedef struct{
	uint8_t u8Cmd;
	uint8_t param0;
	uint8_t param1;
	uint8_t reserved;
}MSG_PTZ_CTRL_REQ;



typedef struct{
	uint32_t reserved;
}MSG_POST_GET_ETH_PARAM_REQ;
typedef struct{
	int32_t result;
	uint32_t reserved;
	ETH_PARAM eth0;
}MSG_POST_GET_ETH_PARAM_RES;
typedef struct{
	ETH_PARAM eth0;
}MSG_POST_SET_ETH_PARAM_REQ;
typedef struct{
	int32_t result;
	uint32_t reserved;
}MSG_POST_SET_ETH_PARAM_RES;





typedef struct{
	uint32_t reserved;
}MSG_POST_GET_PLAT_PARAM_REQ;
typedef struct{
	int32_t result;
	uint32_t reserved;
	FOCUS_CENTER_PARA param;
}MSG_POST_GET_PLAT_PARAM_RES;
typedef struct{
	FOCUS_CENTER_PARA param;
}MSG_POST_SET_PLAT_PARAM_REQ;
typedef struct{
	int32_t result;
	uint32_t reserved;
}MSG_POST_SET_PLAT_PARAM_RES;



typedef struct{
	uint32_t reserved;
}MSG_POST_GET_MQTT_PARAM_REQ;
typedef struct{
	int32_t result;
	uint32_t reserved;
	MQTT_ADAPTER_PARAM param;
}MSG_POST_GET_MQTT_PARAM_RES;
typedef struct{
	MQTT_ADAPTER_PARAM param;
}MSG_POST_SET_MQTT_PARAM_REQ;
typedef struct{
	int32_t result;
	uint32_t reserved;
}MSG_POST_SET_MQTT_PARAM_RES;




typedef struct{
	uint32_t cmd_req;
	uint32_t cmd_resp;
	uint64_t token;
	uint32_t sid;
}SESSION_ASYNC_MSG_INFO;

typedef struct{
	SESSION_ASYNC_MSG_INFO session;
	uint32_t size;   // msg body
	uint8_t data[0]; // msg body size
}MSG_POST_SESSION_ASYNC_REQ;

typedef struct{
	SESSION_ASYNC_MSG_INFO session;
	int32_t result;
	uint32_t size;   // msg body
	uint8_t data[0]; // msg body size
}MSG_POST_SESSION_ASYNC_RESP;

typedef struct{
	uint32_t dhcp;
	char ip[16];
	char mask[16];
}__attribute__((packed))MSG_NVT_SET_IP_REQ;


typedef struct {
	uint8_t	 enable;
	uint8_t	 ShowCheckBox;
	uint32_t Sensitivity;

	uint32_t MaxWidth;
	uint32_t MaxHeight;

	uint32_t MinWidth;
	uint32_t MinHeight;

	uint32_t CurMaxWidth;
	uint32_t CurMaxHeight;

	uint32_t CurMinWidth;
	uint32_t CurMinHeight;

	uint8_t  DstType[32];
}AI_RULES_PARAM;

typedef struct{
	uint32_t reserved;
}MSG_GET_AI_RULES_PARAM;

typedef struct{
	int32_t result;
	AI_RULES_PARAM param;
}MSG_GET_AI_RULES_PARAM_RESULT;

typedef struct{
	AI_RULES_PARAM param;
}MSG_SET_AI_RULES_PARAM;

typedef struct{
	int32_t result;
}MSG_SET_AI_RULES_PARAM_RESULT;

typedef struct{
	int x;
	int y;
}AI_AREA_POINT_T;

#define AI_DETECT_AREA_MAX         (4)
#define AI_DETECT_AREA_POINT_MAX   (7)

typedef struct{
	uint8_t  exist;
	uint8_t  enable;
	AI_AREA_POINT_T points[AI_DETECT_AREA_POINT_MAX];
}AI_AREA_PARAM;

typedef struct{
	AI_AREA_PARAM area[AI_DETECT_AREA_MAX];
}AI_AREAS_PARAM;

typedef struct{
	uint32_t reserved;
}MSG_GET_AI_AREAS_PARAM;

typedef struct{
	int32_t result;
	AI_AREAS_PARAM param;
}MSG_GET_AI_AREAS_PARAM_RESULT;

typedef struct{
	AI_AREAS_PARAM param;
}MSG_SET_AI_AREAS_PARAM;

typedef struct{
	int32_t result;
}MSG_SET_AI_AREAS_PARAM_RESULT;


typedef struct {
	uint8_t	 LightEnable;
	uint32_t LightFlashDuration;

	uint8_t	 SoundEnable;
	uint32_t SoundIndex;
	uint32_t SoundPlayCount;

	uint32_t AlarmOutCount;
	uint32_t AlarmOutEnable[8];
}AI_ALARM_LINKAGE_PARAM;

typedef struct{
	uint32_t reserved;
}MSG_GET_AI_ALARM_LINKAGE_PARAM;

typedef struct{
	int32_t result;
	AI_ALARM_LINKAGE_PARAM param;
}MSG_GET_AI_ALARM_LINKAGE_PARAM_RESULT;

typedef struct{
	AI_ALARM_LINKAGE_PARAM param;
}MSG_SET_AI_ALARM_LINKAGE_PARAM;

typedef struct{
	int32_t result;
}MSG_SET_AI_ALARM_LINKAGE_PARAM_RESULT;



#define LINKAGE_SOUND_LIST_MAX_COUNT  10

typedef struct{
	char name[64];
}LINKAGE_SOUND_LIST_ITEM;

typedef struct{
	uint32_t count;  //List Item Number
	LINKAGE_SOUND_LIST_ITEM list[LINKAGE_SOUND_LIST_MAX_COUNT];
}LINKAGE_SOUND_LIST;

typedef struct{
	uint32_t reserved;
}MSG_GET_LINKAGE_SOUND_LIST_REQ;

typedef struct{
	int32_t result;
	LINKAGE_SOUND_LIST param;
}MSG_GET_LINKAGE_SOUND_LIST_RESP;


typedef struct{
	uint32_t reserved;
}__attribute__((packed))MSG_BROADCAST_AI_DETECT_STOPED;



typedef struct{
	int32_t result;
}__attribute__((packed))MSG_NVT_SET_IP_RSP;



typedef struct{
	char default_gw[16];
}__attribute__((packed))MSG_NVT_SET_DEFAULT_GW_REQ;


typedef struct{
	int32_t result;
}__attribute__((packed))MSG_NVT_SET_DEFAULT_GW_RSP;


typedef struct{
	int32_t reserved;
}__attribute__((packed))BROADCAST_MSG_NETWORK_CHANGED_BY_NVT;

typedef struct{
	uint32_t enable;
}__attribute__((packed))BROADCAST_MSG_WIFI_ENABLE_MSG;

typedef struct{
	uint32_t reserved;
}__attribute__((packed))BROADCAST_MSG_SOS_TRIGGER_ACTIVE_MSG;


typedef struct{
	uint32_t reserved;
}__attribute__((packed))POST_MSG_QUERY_FH_WIFI_QUIRK_MSG;

typedef struct{
	uint32_t quirk;
}__attribute__((packed))POST_MSG_QUERY_FH_WIFI_QUIRK_RESP_MSG;



typedef struct{
	int32_t mode;
	int32_t cdsDayThreshold;
	int32_t cdsNightThreshold;
	int32_t aeDayThreshold;
	int32_t aeNightThreshold;
	int32_t timerDayThreshold;
	int32_t timerNightThreshold;
}IRCUT_PARAM;

typedef struct{
	int32_t reserved;
}MSG_GET_IRCUT_PARAM;

typedef struct{
	int32_t result;
	IRCUT_PARAM param;
}MSG_GET_IRCUT_PARAM_RESULT;

typedef struct{
	IRCUT_PARAM param;
}MSG_SET_IRCUT_PARAM;

typedef struct{
	int32_t result;
}MSG_SET_IRCUT_PARAM_RESULT;



typedef struct{
	int32_t floor;
}MSG_POST_LIFT_MOVE_REQ;


typedef struct{
	int32_t reserved;
}MSG_UPDATE_ETH_LINK_STATUS_REQ;

typedef struct{
    int32_t state;
}__attribute__((packed))MSG_BROADCAST_SET_WHITE_LIGHT_STATE;

typedef struct{
	ENUM_FACE_TYPE enFaceType;
	uint8_t labelID[64];
	uint8_t picID[64];
}MSG_POST_HUIYUN_DEL_FACE_REQ;

typedef struct{
	ENUM_FACE_TYPE enFaceType;
	uint8_t labelID[64];
	uint8_t picID[64];
}MSG_POST_HUIYUN_MODIFY_FACE_BELONG_REQ;

typedef struct{
	void * pCmsPlaybackService;
	void * pParentSession;
}MSG_BROADCAST_CMS_PLAYBACK_SERVICE_EXIT;


typedef struct{
	int32_t reserved;
}MSG_GET_DB_FACE_COUNT_REQ;

typedef struct{
	int32_t result;
	int32_t count;
}MSG_GET_DB_FACE_COUNT_RESULT;


typedef struct{
	int32_t reserved;
}MSG_GET_DAY_NIGHT_STATUS_REQ;

typedef struct{
	int32_t result;
	int32_t status;
}MSG_GET_DAY_NIGHT_STATUS_RESULT;

typedef struct{
	int status;
}MSG_POST_DAY_NIGHT_STATUS_REQ;

typedef enum{
	enum_huiyun_del_face_result_successfully			= 0,
	enum_huiyun_del_face_result_face_id_not_exist		= -1,
	enum_huiyun_del_face_result_sdk_not_ready			= -2,
	enum_huiyun_del_face_result_type_invalid			= -3,
	enum_huiyun_del_face_result_failed					= -4,
}ENUM_HUIYUN_DEL_FACE_RESULT;

typedef enum{
	enum_huiyun_edit_face_result_successfully			= 0,
	enum_huiyun_edit_face_result_face_not_exist			= -1,
	enum_huiyun_edit_face_result_param_invalid			= -2,
	enum_huiyun_edit_face_result_sdk_not_ready			= -3,
	enum_huiyun_edit_face_result_face_type_invalid		= -4,
}ENUM_HUIYUN_EDIT_FACE_RESULT;

typedef struct{
	int32_t result; // ENUM_HUIYUN_DEL_FACE_RESULT
}__attribute__((packed))MSG_POST_HUIYUN_DEL_FACE_RESULT;

typedef struct{
	int32_t result; // ENUM_HUIYUN_EDIT_FACE_RESULT
}__attribute__((packed))MSG_POST_HUIYUN_EDIT_FACE_RESULT;


typedef enum{
	enum_snapshot_result_successfully	= 0,
	enum_snapshot_result_failed			= -1,
}ENUM_SNAPSHOT_RESULT;

typedef struct{
	int32_t result; //ENUM_SNAPSHOT_RESULT
}__attribute__((packed))MSG_POST_SNAPSHOT_RESULT;


typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_GET_FACE_COMPARE_PARAM_REQ;

typedef struct{
	int32_t result;
	float threshold;
}__attribute__((packed))MSG_GET_FACE_COMPARE_PARAM_RESULT;

typedef struct{
	float threshold;
}__attribute__((packed))MSG_SET_FACE_COMPARE_PARAM_REQ;

typedef struct{
	int32_t result;
}__attribute__((packed))MSG_SET_FACE_COMPARE_PARAM_RESULT;


typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_GET_SIM_ICCID_REQ;

typedef struct{
	uint8_t iccid[64];
	int32_t result;
}__attribute__((packed))MSG_GET_SIM_ICCID_RESULT;

typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_GET_IMEI_REQ;

typedef struct{
	uint8_t imei[64];
	int32_t result;
}__attribute__((packed))MSG_GET_IMEI_RESULT;

typedef struct{
	uint32_t enable;
}__attribute__((packed))MSG_SET_GPRS_STATUS;

typedef struct{
	int32_t reserved;
}__attribute__((packed))MSG_GET_4G_SIGNALE_QUALITY_REQ;

typedef struct{
	int32_t signal_quality;
	int32_t result;
}__attribute__((packed))MSG_GET_4G_SIGNALE_QUALITY_RESULT;


typedef struct{
	int32_t reserved;
}MSG_BROADCAST_TIME_ZONE_CHANGED;


#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* End of #ifdef __cplusplus */

#endif /* End of #ifndef __IPCMSG_DATA_TYPE_H__ */





