
#MSC313E
#CROSS_COMPILE:=arm-linux-gnueabihf-
#HI3516EV200
#CROSS_COMPILE:=arm-himix100-linux-
#SSC335
#CROSS_COMPILE:=arm-buildroot-linux-uclibcgnueabihf-
#SSC338
#CROSS_COMPILE:=arm-linux-gnueabihf-9.1.0-
#SV823
#CROSS_COMPILE:=arm-linux-gnueabihf-7.5.0-

#FH8852
CROSS_COMPILE=arm-fullhanv2-linux-uclibcgnueabi-


CC:=$(CROSS_COMPILE)gcc
CXX:=$(CROSS_COMPILE)g++
AR:=$(CROSS_COMPILE)ar
STRIP:=$(CROSS_COMPILE)strip
